{{- if eq .Values.global.domain.gateway_type "istio"  }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: ohcore-webcomponents-integration-front-virtual-service
spec:
  gateways:
    - oh-modules-gateway
  hosts:
    - '{{ .Values.global.domain.host }}'
  http:
    - headers:
        request:
          set:
            x-forwarded-host: {{ .Values.global.domain.host }}
            x-forwarded-port: '{{ if eq .Values.global.domain.protocol "http" }}80{{ else if eq .Values.global.domain.protocol "https" }}443{{ end }}'
            x-forwarded-proto: {{ .Values.global.domain.protocol }}
      match:
        - uri:
            prefix: /ohcore-webcomponents-integration/
      route:
        - destination:
            host: ohcore-webcomponents-integration-front
            port:
              number: 8080
    - match:
        - uri:
            prefix: /ohcore-webcomponents-integration/
      route:
        - destination:
            host: ohcore-webcomponents-integration-front
            port:
              number: 8080
    - match:
        - uri:
            prefix: /ohcore-webcomponents-integration
      rewrite:
        uri: /ohcore-webcomponents-integration/
      route:
        - destination:
            host: ohcore-webcomponents-integration-front
            port:
              number: 8080
{{- end }}