apiVersion: v1
kind: Service
metadata:
  name: ohaut-back
  labels:
    app: ohaut-back
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: ohaut-back
