{{- if eq .Values.global.domain.gateway_type "k8s_gateway"  }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ohaut-http-route
spec:
  hostnames:
    - {{ .Values.global.domain.host }}
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: oh-modules-gateway
      sectionName: oh-modules
  rules:
    - backendRefs:
        - group: ''
          kind: Service
          name: ohaut-back
          namespace: {{ .Release.Namespace }}
          port: 8080
          weight: 1
      filters:
        - requestHeaderModifier:
            set:
              - name: X-Forwarded-Host
                value: {{ .Values.global.domain.host }}
              - name: X-Forwarded-Proto
                value: {{ .Values.global.domain.protocol }}
              - name: X-Forwarded-Port
                value: '{{ if eq .Values.global.domain.protocol "http" }}80{{ else if eq .Values.global.domain.protocol "https" }}443{{ end }}'
          type: RequestHeaderModifier
      matches:
        - path:
            type: PathPrefix
            value: /hnaut/fhir/
        - path:
            type: PathPrefix
            value: /hnaut/fhir
        - path:
            type: PathPrefix
            value: /hnaut/fhir/$login
        - path:
            type: PathPrefix
            value: /hnaut/fhir/$changePassword
        - path:
            type: PathPrefix
            value: /hnaut/fhir/AccessOption
        - path:
            type: PathPrefix
            value: /hnaut/StreamServlet/
        - path:
            type: Exact
            value: /hnaut/keycloak.json
        - path:
            type: Exact
            value: /hnaut/healthcheck
    - backendRefs:
        - group: ''
          kind: Service
          name: ohaut-front
          namespace: {{ .Release.Namespace }}
          port: 8080
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /hnaut

{{- end }}