kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.ohgen.app.name_front }}
  labels:
    app: {{ .Values.ohgen.app.name_front }}
spec:
  replicas: {{ .Values.ohgen.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.ohgen.app.name_front }}
  template:
    metadata:
      labels:
        app: {{ .Values.ohgen.app.name_front }}
      annotations:
        sidecar.istio.io/inject: 'false'
    spec:
      restartPolicy: Always
      serviceAccountName: oh-module
      imagePullSecrets:
        - name: {{ .Values.global.docker.registry.secret }}
      {{- if .Values.global.domain.ip }}
      hostAliases:
        - ip: {{ .Values.global.domain.ip }}
          hostnames:
            - {{ .Values.global.domain.host }}
      {{- end }}
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      securityContext: {}
      containers:
        - resources:
            limits:
              cpu: 50m
              memory: 48Mi
            requests:
              cpu: 25m
              memory: 16Mi
          readinessProbe:
            httpGet:
              path: /dsforms/index.html
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 1
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: {{ .Values.ohgen.app.name_front }}
          livenessProbe:
            httpGet:
              path: /dsforms/index.html
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: {{ .Values.ohgen.app.name_front }}-cfg
              readOnly: true
              mountPath: /usr/share/nginx/html/dsforms/assets/config
            - name: ohgen-front-i18n
              readOnly: true
              mountPath: /usr/share/nginx/html/dsforms/res/i18n
            - name: hnhome-ohsso-front
              readOnly: true
              mountPath: /usr/share/nginx/html/dsforms/keycloak.json
              subPath: keycloak.json
            - name: nginx-front-cfg
              readOnly: true
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          terminationMessagePolicy: File
          image: '{{ .Values.global.docker.registry.host }}/{{ .Values.global.docker.registry.project }}/ohgen-front:{{ .Values.ohgen.version.front_image_tag }}'
      serviceAccount: oh-module
      volumes:
        - name: {{ .Values.ohgen.app.name_front }}-cfg
          configMap:
            name: {{ .Values.ohgen.app.name_front }}-cfg
            defaultMode: 420
        - name: ohgen-front-i18n
          configMap:
            name: ohgen-front-i18n
            defaultMode: 420
        - name: hnhome-ohsso-front
          configMap:
            name: hnhome-ohsso-front
            defaultMode: 420
        - name: nginx-front-cfg
          configMap:
            name: nginx-front-cfg
            defaultMode: 420
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
