kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.ohbpm.app.name }}-designer-front
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: {{ .Values.ohbpm.app.name }}-designer-front
