apiVersion: v1
kind: ConfigMap
metadata:
  name: 'ohsso-configmap-global'
data:
  keycloak.conf: |-
    # build
    db={{ .Values.global.database.type }}
    http-enabled=true
    health-enabled=true
    http-relative-path=auth
    # cache=local|ispn 
    cache=ispn
    cache-stack=kubernetes
    # cache-config-file=cache-kubernetes.xml
    features=scripts
    metrics-enabled=true
    # run
    hostname={{ .Values.global.domain.host }}
    proxy=passthrough
    http-port=8080
    {{- if eq .Values.global.database.type "mysql" }}
    db-url=jdbc:mysql://{{ .Values.global.database.host }}:{{ .Values.global.database.port }}/{{ .Values.ohsso.db.schema }}{{ .Values.global.database.properties }}
    {{- else if eq .Values.global.database.type "oracle" }}
    db-url=jdbc:oracle:thin:@{{ .Values.global.database.host }}:{{ .Values.global.database.port }}:{{ .Values.global.database.oracle_sid }}{{ .Values.global.database.properties }}
    {{- end }}
    db-username={{ .Values.ohsso.db.user }}
    db-password={{ .Values.ohsso.db.pass }}
    log=console
    log-level=INFO,es.indra:INFO,com.minsait:INFO
    spi-login-protocol-openid-connect-legacy-logout-redirect-uri=true
    spi-user-storage-provider-timeout=12000