{{- if eq .Values.global.domain.gateway_type "k8s_gateway"  }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ohsso-http-route
spec:
  hostnames:
    - {{ .Values.global.domain.host }}
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: oh-modules-gateway
      sectionName: oh-modules
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /auth/metrics
      backendRefs:
        - group: ''
          kind: Service
          name: error-404
          namespace: {{ .Release.Namespace }}
          port: 8080
    - matches:
        - path:
            type: RegularExpression
            value: ^/auth/realms/.*/metrics.*
      backendRefs:
        - group: ''
          kind: Service
          name: error-404
          namespace: {{ .Release.Namespace }}
          port: 8080
    - backendRefs:
        - group: ''
          kind: Service
          name: ohsso
          namespace: {{ .Release.Namespace }}
          port: 8080
          weight: 1
      filters:
        - requestHeaderModifier:
            set:
              - name: X-Forwarded-Host
                value: {{ .Values.global.domain.host }}
              - name: X-Forwarded-Proto
                value: {{ .Values.global.domain.protocol }}
              - name: X-Forwarded-Port
                value: '{{ if eq .Values.global.domain.protocol "http" }}80{{ else if eq .Values.global.domain.protocol "https" }}443{{ end }}'
          type: RequestHeaderModifier
      matches:
        - path:
            type: PathPrefix
            value: /auth
{{- end }}