apiVersion: v1
kind: ConfigMap
metadata:
  name: 'ohsso-configmap-realm-oh-base'
data:
  integration.properties: |-
    hnpob.fhir.url=http://ohmpi-back:8080/ispob/fhir/  
    hnaut.fhir.url=http://ohmpi-back:8080/hnaut/fhir/
    hncat.fhir.url=http://ohont-back:8080/hncat/fhir/
    hnconf.fhir.url=http://ohcon-back:8080/hnconf/fhir/
    homec.fhir.url=http://ohhom-back:8080/ohhom/fhir/
    keycloak.url.initial={{ .Values.global.domain.protocol }}://{{ .Values.global.domain.host }}/realms/oh-base/protocol/openid-connect/token
    keycloak.client.id=hnrole
    ohsso.provider.core.lastlogin.enabled=true
    ohsso.provider.core.lastlogin.format=yyyy/MM/dd HH:mm
    ohsso.provider.core.lastlogin.excludedclientids=
    ohsso.provider.core.lastlogin.excludeduserprovidernames=mymed-storage-external-token
    error.user.noroles=El usuario no tiene roles asignados.
    error.user.nocenters=El usuario no tiene centros asignados.
    error.user.noaccess=El usuario no tiene permiso de aceso.
    error.internal=Se ha producido un error interno.
    error.user.authentication=Autenticacion de usuario incorrecta.
    keycloak.listener.hnatna.enabled=true
    keycloak.listener.hnatna.appname=AUTH
    keycloak.listener.hnatna.facility=AUDIT
    keycloak.listener.hnatna.format=RFC5424
    keycloak.listener.hnatna.severity=INFORMATIONAL
    keycloak.listener.hnatna.ssl=false
    keycloak.listener.hnatna.notifyevents=LOGIN,LOGOUT,LOGIN_ERROR,LOGOUT_ERROR,CLIENT_LOGIN,CLIENT_LOGIN_ERROR
    keycloak.listener.hnatna.sourcesystem=OH_SSO
    keycloak.listener.hnatna.port=2862
    keycloak.listener.hnatna.protocol=TCP
    keycloak.listener.hnatna.sysloghost=ohatn-back
    external.token.verify.signature=false
    external.token.verify.signature.launch=false
    external.token.verify.signature.endpoint=false
    external.token.default.kid=???
    external.token.error.general=Error interno.
    external.token.error.invalid_token=Error: token invalido.
    external.token.error.invalid_signature=Error: firma invalida.
    external.token.error.token_required=Error: subject_token es requerido.
    external.token.error.sub_required=Error: campo sub es requerido.
    external.token.error.invalid_kid=Error: KID invalido. 
    external.token.error.exp_date_required=Error. Fecha de expiracion del token es requerida.
    external.token.error.exp_date_exceeded=Error. Token expirado.
    # configuracion para ohsso-provider-patient
    ohsso.provider.patient.light.endpoint.enabled=true
    ohsso.provider.patient.otp.endpoint.enabled=true
    ohsso.provider.patient.light.role.code=PACIENTE_BASICO
    ohsso.provider.patient.otp.role.code=PACIENTE_AVANZADO
    ohsso.provider.patient.light.error.general=General error in patient light login.
    ohsso.provider.patient.light.error.mirth.general=Generar error in patient search service.
    #ohsso.provider.patient.light.error.mirth.<code>=
    ohsso.provider.patient.light.error.patient_not_found=Paciente no encontrado.
    ohsso.provider.patient.light.error.invalid_params=Petici\u00f3n incorrecta, faltan par\u00e1metros.
    ohsso.provider.patient.light.error.multiple_patients_found=M\u00e1s de un paciente encontrado
    ohsso.provider.patient.otp.code.length=6
    ohsso.provider.patient.otp.code.ttl=600
    #com.minsait.onesait.healthcare.ohsso.provider.patient.HttpSMSOTPSender, HttpEmailOTPSender
    ohsso.provider.patient.otp.sender.class=com.minsait.onesait.healthcare.ohsso.provider.patient.HttpSMSOTPSender
    ohsso.provider.patient.otp.sender.sms.http.url=https://dummy.oh.es/sms-send-dummy
    ohsso.provider.patient.otp.sender.sms.message=OHSSO: su password temporal de acceso es %CODE%
    ohsso.provider.patient.otp.sender.email.http.url=https://dummy.oh.es/email-send-dummy
    ohsso.provider.patient.otp.sender.email.message=OHSSO: su password temporal de acceso es %CODE%
    ohsso.provider.patient.otp.error.patient_not_found=Paciente no encontrado.      
    ohsso.provider.patient.otp.error.invalid_params=Petici\u00f3n incorrecta, faltan par\u00e1metros.
    ohsso.provider.patient.otp.error.multiple_patients_found=M\u00e1s de un paciente encontrado
    ohsso.provider.patient.otp.error.sending_code=Error enviando c\u00f3digo de verificaci\u00f3n.
    ohsso.provider.patient.otp.error.no_mobile_number=No se tiene registrado tel\u00e9fono m\u00f3vil para el paciente.
    ohsso.provider.patient.otp.error.code_expired=C\u00f3digo de verificaci\u00f3n expirado.
    ohsso.provider.patient.otp.error.code_invalid=El c\u00f3digo de verificaci\u00f3n introducido no es correcto.
    ohsso.provider.patient.behalf.consenttype=APP
    ohsso.provider.patient.consent.service.url=http://ohcsm-back:8080/ohcsm/api/fhir
    ohsso.provider.patient.behalf.light.role.code.cuidador=CUIDADOR_BASICO
    ohsso.provider.patient.behalf.light.role.code.replegal=REPLEG_BASICO
    ohsso.provider.patient.behalf.otp.role.code.cuidador=CUIDADOR_AVANZADO
    ohsso.provider.patient.behalf.otp.role.code.replegal=REPLEG_AVANZADO
  password.properties: |-
    keycloak.login.client_id=ohsso
    keycloak.login.client_secret=6r5GMS3zEfhuTwvW2gGHCMGYlm7Vk1Uo