apiVersion: v1
kind: Service
metadata:
  name: 'ohsso-jgroups-ping'
  labels:
    service: 'ohsso-keycloak'
spec:
  ports:
    - name: ping
      protocol: TCP
      port: 4444
      targetPort: 4444
  selector:
    app: 'ohsso'
  sessionAffinity: None
  clusterIP: None