apiVersion: v1
kind: Service
metadata:
  name: 'ohsso'
  labels:
    service: 'ohsso'
    app: ohsso
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: 'ohsso'
