kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: ohgeneric-form-front-template
objects:
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: ${OHGENERIC_FORM_WEBCOMPONENT_APP}
      namespace: ${OHGENERIC_FORM_NAMESPACE}
      labels:
        app: ${OHGENERIC_FORM_WEBCOMPONENT_APP}
    spec:
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 25%
          maxSurge: 25%
        resources: {}
      replicas: 1
      selector:
        matchLabels:
          app: ${OHGENERIC_FORM_WEBCOMPONENT_APP}
      template:
        metadata:
          labels:
            app: ${OHGENERIC_FORM_WEBCOMPONENT_APP}
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          imagePullSecrets:
            - name: ${DOCKER_REGISTRY}
          serviceAccountName: oh-module
          containers:
            - name: ${OHGENERIC_FORM_WEBCOMPONENT_APP}
              image: ${DOCKER_REGISTRY}/${DOCKER_REGISTRY_PROJECT}/ohgeneric-form-webcomponents:${OHGENERIC_FORM_WEBCOMPONENT_IMAGE_TAG}
              ports:
                - containerPort: 8080
                  protocol: TCP

              livenessProbe:
                httpGet:
                  path: /ohgeneric-form-webcomponents/remoteEntry.js
                  port: 8080
                initialDelaySeconds: 20
                periodSeconds: 10

              readinessProbe:
                httpGet:
                  path: /ohgeneric-form-webcomponents/remoteEntry.js
                  port: 8080
                initialDelaySeconds: 60
                periodSeconds: 20

              volumeMounts:
                - name: nginx-front-cfg
                  readOnly: true
                  mountPath: /etc/nginx/nginx.conf
                  subPath: nginx.conf

                - name: nginx-front-cfg
                  readOnly: true
                  mountPath: /etc/nginx/conf.d/default.conf
                  subPath: default.conf

              resources:
                limits:
                  cpu: 50m
                  memory: 48Mi
                requests:
                  cpu: 25m
                  memory: 16Mi
              imagePullPolicy: Always

          volumes:
            - name: nginx-front-cfg
              configMap:
                name: nginx-front-cfg
                defaultMode: 420

  - kind: Service
    apiVersion: v1
    metadata:
      name: ${OHGENERIC_FORM_WEBCOMPONENT_APP}
      namespace: ${OHGENERIC_FORM_NAMESPACE}
    spec:
      ports:
        - name: http
          protocol: TCP
          port: 8080
          targetPort: 8080
      selector:
        app: ${OHGENERIC_FORM_WEBCOMPONENT_APP}

  - kind: VirtualService
    apiVersion: networking.istio.io/v1beta1
    metadata:
      name: ${OHGENERIC_FORM_WEBCOMPONENT_APP}-virtual-service
      namespace: ${OHGENERIC_FORM_NAMESPACE}
    spec:
      gateways:
        - oh-modules-gateway
      hosts:
        - "*"
      http:
        - headers:
            request:
              set:
                x-forwarded-host: ${OHGENERIC_FORM_NAMESPACE}.apps.lab.openshift.com
                x-forwarded-port: "443"
                x-forwarded-proto: https
          match:
            - uri:
                prefix: /ohgeneric-form-webcomponents/
          route:
            - destination:
                host: ${OHGENERIC_FORM_WEBCOMPONENT_APP}
                port:
                  number: 8080
        - match:
            - uri:
                prefix: /ohgeneric-form-webcomponents/
          route:
            - destination:
                host: ${OHGENERIC_FORM_WEBCOMPONENT_APP}
                port:
                  number: 8080

parameters:
  - description: Docker registry
    displayName: Docker registry
    name: DOCKER_REGISTRY
    value: docksdtr.indra.es
    required: true
  - description: Docker registry project
    displayName: Docker registry project
    name: DOCKER_REGISTRY_PROJECT
    value: multhn_cmhn20_2
    required: true
  - name: OHGENERIC_FORM_NAMESPACE
    displayName: Namespace Entorno
    description: Namespace Entorno
    value: "oh-release"
    required: true
  - name: OHGENERIC_FORM_WEBCOMPONENT_APP
    displayName: OHGENERIC_FORM Webcomponent application name
    description: Name or alias to identify application OHGENERIC_FORM webcomponent
    value: ohgeneric-form-webcomponents-front
    required: true
  - name: OHGENERIC_FORM_WEBCOMPONENT_IMAGE_TAG
    displayName: Image tag
    description: Image tag
    value: "dev"
    required: true
