kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: webcomponent-viewer-front-template
objects:

  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: ${OHWCV_FRONT_APP}-cfg
      namespace: ${OHWCV_NAMESPACE}
    data:
      env.json: |-
        {
          "services_host": "https://${OHWCV_HOST}",
          "keycloak-js-dist": "https://${OHWCV_HOST}/webcomponent-viewer/ohsso-lib.js",
          "app_theme": "./assets/css/themes/default"
        }


  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: ${OHWCV_FRONT_APP}-i18n
      namespace: ${OHWCV_NAMESPACE}
    data:
      es.json: |-
        {
        "label.module.not.found": "Modulo no configurado",
        "label.option.not.found": "Opción no configurada"
        }

      en.json: |-
        {
        "label.module.not.found": "Module not configured",
        "label.option.not.found": "Option not configured"
        }

      ca.json: |-
        {
        }


  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: ${OHWCV_FRONT_APP}-keycloak-cfg
      namespace: ${OHWCV_NAMESPACE}
    data:
      keycloak.json: |-
        {
          "realm" : "${OHSSO_REALM}",
          "resource" : "${OHSSO_CLIENT_ID}",
          "public-client": true,
          "auth-server-url": "${OHSSO_PROTOCOL}://${OHSSO_HOST}/auth",
          "enable-cors": true
        }

  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: ${OHWCV_FRONT_APP}
      namespace: ${OHWCV_NAMESPACE}
      labels:
        app: ${OHWCV_FRONT_APP}
    spec:
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 25%
          maxSurge: 25%
        resources: {}
      replicas: 1
      selector:
        matchLabels:
          app: ${OHWCV_FRONT_APP}
      template:
        metadata:
          labels:
            app: ${OHWCV_FRONT_APP}
          annotations:
            sidecar.istio.io/inject: 'false'
        spec:
          imagePullSecrets:
            - name: ${DOCKER_REGISTRY}
          serviceAccountName: oh-module
          containers:
            - name: ${OHWCV_FRONT_APP}
              image: ${DOCKER_REGISTRY}/${DOCKER_REGISTRY_PROJECT}/webcomponent-viewer:${OHWCV_FRONT_IMAGE_TAG}
              ports:
                - containerPort: 8080
                  protocol: TCP

              livenessProbe:
                httpGet:
                  path: /webcomponent-viewer/index.html
                  port: 8080
                initialDelaySeconds: 20
                periodSeconds: 10

              readinessProbe:
                httpGet:
                  path: /webcomponent-viewer/index.html
                  port: 8080
                initialDelaySeconds: 60
                periodSeconds: 20

              volumeMounts:
                - name: ${OHWCV_FRONT_APP}-cfg
                  mountPath: /usr/share/nginx/html/webcomponent-viewer/assets/config
                  readOnly: true

                - name: ${OHWCV_FRONT_APP}-i18n
                  mountPath: /usr/share/nginx/html/webcomponent-viewer/assets/i18n
                  readOnly: true

                - name: ${OHWCV_FRONT_APP}-keycloak-cfg
                  mountPath: /usr/share/nginx/html/webcomponent-viewer/keycloak.json
                  subPath: keycloak.json
                  readOnly: true

                - name: nginx-front-cfg
                  readOnly: true
                  mountPath: /etc/nginx/nginx.conf
                  subPath: nginx.conf
                - name: ohsso-lib
                  readOnly: true
                  mountPath: /usr/share/nginx/html/webcomponent-viewer/ohsso-lib.js
                  subPath: ohsso-lib.js

              resources:
                limits:
                  cpu: 50m
                  memory: 48Mi
                requests:
                  cpu: 25m
                  memory: 16Mi
              imagePullPolicy: Always

          volumes:
            - name: ${OHWCV_FRONT_APP}-cfg
              configMap:
                name: ${OHWCV_FRONT_APP}-cfg

            - name: ${OHWCV_FRONT_APP}-i18n
              configMap:
                name: ${OHWCV_FRONT_APP}-i18n
            - name: ${OHWCV_FRONT_APP}-keycloak-cfg
              configMap:
                name: ${OHWCV_FRONT_APP}-keycloak-cfg
            - name: nginx-front-cfg
              configMap:
                name: nginx-front-cfg
                defaultMode: 420
            - name: ohsso-lib
              configMap:
                name: ohsso-lib
                defaultMode: 420


  - kind: Service
    apiVersion: v1
    metadata:
      name: ${OHWCV_FRONT_APP}
      namespace: oh-modules
    spec:
      ports:
        - name: http
          protocol: TCP
          port: 8080
          targetPort: 8080
      selector:
        app: ${OHWCV_FRONT_APP}

  - kind: VirtualService
    apiVersion: networking.istio.io/v1beta1
    metadata:
      name: ${OHWCV_FRONT_APP}-virtual-service
      namespace: ${OHWCV_NAMESPACE}
    spec:
      gateways:
        - oh-modules-gateway
      hosts:
        - '*'
      http:
        - headers:
            request:
              set:
                x-forwarded-host: oh-modules.apps.lab.openshift.com
                x-forwarded-port: '443'
                x-forwarded-proto: https
          match:
            - uri:
                prefix: /webcomponent-viewer/
          route:
            - destination:
                host: ${OHWCV_FRONT_APP}
                port:
                  number: 8080
        - match:
            - uri:
                prefix: /webcomponent-viewer/
          route:
            - destination:
                host: ${OHWCV_FRONT_APP}
                port:
                  number: 8080
        - match:
            - uri:
                exact: /webcomponent-viewer
          rewrite:
            uri: /webcomponent-viewer/
          route:
            - destination:
                host: ${OHWCV_FRONT_APP}
                port:
                  number: 8080


parameters:
  - description: Docker registry
    displayName: Docker registry
    name: DOCKER_REGISTRY
    value: docksdtr.indra.es
    required: true
  - description: Docker registry project
    displayName: Docker registry project
    name: DOCKER_REGISTRY_PROJECT
    value: multhn_cmhn20_2
    required: true
  - description: SSO realm
    displayName: SSO realm
    name: OHSSO_REALM
    required: true
  - description: Host where OHSSO is exposed (generally it will be the host defined in the oh-modules Gateway).
    displayName: Host where OHSSO is exposed
    name: OHSSO_HOST
    required: true
  - description: Protocol which OHSSO is exposed (http|https). Generally it will be the protocol defined in the oh-modules Gateway.
    displayName: Protocol which OHSSO is exposed (http|https)
    name: OHSSO_PROTOCOL
    value: https
  - description: SSO client_id access
    displayName: SSO client_id access
    name: OHSSO_CLIENT_ID
  - name: OHWCV_HOST
    displayName: Url host entorno
    description: Url host entorno
    value: 'oh-release.apps.lab.openshift.com'
    required: true
  - name: OHWCV_FRONT_APP
    displayName:  OHWCV front application name
    description: Name or alias to identify application OHWCV front
    value: webcomponent-viewer-front
  - name: OHWCV_NAMESPACE
    displayName: Namespace Entorno
    description: Namespace Entorno
    value: 'oh-release'
    required: true  
  - name: OHWCV_FRONT_IMAGE_TAG
    displayName: Image tag for OHWCV visor
    description: Image tag for OHWCV visor
    value: '4.0.0'
    required: true



