apiVersion: v1
kind: Service
metadata:
  labels:
    app: 'ohien-control-panel'
    search: pipeline-streams
    tier: backend
  name: ohien-pipeline-handler
spec:
  ports:
    - name: http-backend
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: ohien-pipeline-handler
