apiVersion: v1
kind: Service
metadata:
  labels:
    app: 'ohien-control-panel'
  name: 'ohien-control-panel'
spec:
  ports:
    - name: http-backend
      port: 8081
      protocol: TCP
      targetPort: 8081
    - name: http-frontend
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: 'ohien-control-panel'
