apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: 'ohien-control-panel-rb'
  labels:
    app: 'ohien-control-panel'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    name: 'ohien-control-panel'
