kind: Deployment
apiVersion: apps/v1
metadata:
  name: ohien-pipeline-handler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ohien-pipeline-handler
  template:
    metadata:
      labels:
        app: ohien-pipeline-handler
    spec:
      restartPolicy: Always
      securityContext: {}
      imagePullSecrets:
        - name: 'oh-docker-creds'
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      containers:
        - name: ohien-pipeline-handler
          image: '{{ .Values.registry.host }}/{{ .Values.registry.project }}/ohien-control-panel-handler:streams'
          ports:
            - containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /pipelinestatus/actuator/health/liveness
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 20
            timeoutSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /pipelinestatus/actuator/health/readiness
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 20
            timeoutSeconds: 10
            failureThreshold: 5
          resources:
            limits:
              cpu: 150m
              memory: 1200Mi
            requests:
              cpu: 100m
              memory: 256Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      serviceAccount: 'ohien-control-panel'
      dnsPolicy: ClusterFirst
