{{- if .Values.istio.enabled  }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  labels:
    app: 'ohien-control-panel'
  name: 'ohien-control-panel'
spec:
  gateways:
    - oh-modules-gateway
  hosts:
    - '{{ .Values.general.host }}'
  http:
    - corsPolicy:
        allowHeaders:
          - x-requested-with
          - Content-Type
          - jwtheader
          - Origin
          - authorization
          - accept
          - client-security-token
          - x-preserve-id
          - if-none-exist
          - prefer
          - Referer
        allowMethods:
          - GET
          - POST
          - OPTIONS
          - PUT
          - DELETE
        allowOrigin:
          - '{{ .Values.general.protocol }}://{{ .Values.general.host }}'
      headers:
        request:
          set:
            X-Forwarded-Host: '{{ .Values.general.host }}'
            X-Forwarded-Port: '{{ .Values.general.port }}'
            X-Forwarded-Proto: '{{ .Values.general.protocol }}'
        response:
          set:
            referrer-policy: no-referer-when-downgrade
      match:
        - uri:
            prefix: /ohien/api/
        - uri:
            prefix: /ohien/api
      route:
        - destination:
            host: 'ohien-control-panel'
            port:
              number: 8081
    - corsPolicy:
        allowHeaders:
          - x-requested-with
          - Content-Type
          - jwtheader
          - Origin
          - authorization
          - accept
          - client-security-token
          - x-preserve-id
          - if-none-exist
          - prefer
          - Referer
        allowMethods:
          - GET
          - POST
          - OPTIONS
          - PUT
          - DELETE
        allowOrigin:
          - '{{ .Values.general.protocol }}://{{ .Values.general.host }}'
      headers:
        request:
          remove:
            - authorization
          set:
            X-Forwarded-Host: '{{ .Values.general.host }}'
            X-Forwarded-Port: '{{ .Values.general.port }}'
            X-Forwarded-Proto: '{{ .Values.general.protocol }}'
        response:
          set:
            referrer-policy: no-referer-when-downgrade
      match:
        - uri:
            prefix: /ohien/connectors/
        - uri:
            prefix: /ohien/connectors
      rewrite:
        uri: /connectors/
      route:
        - destination:
            host: 'ohien-kafka-connect'
            port:
              number: 8083
    - corsPolicy:
        allowHeaders:
          - x-requested-with
          - Content-Type
          - jwtheader
          - Origin
          - authorization
          - accept
          - client-security-token
          - x-preserve-id
          - if-none-exist
          - prefer
          - Referer
        allowMethods:
          - GET
          - POST
          - OPTIONS
          - PUT
          - DELETE
        allowOrigin:
          - '{{ .Values.general.protocol }}://{{ .Values.general.host }}'
      headers:
        request:
          remove:
            - authorization
          set:
            X-Forwarded-Host: '{{ .Values.general.host }}'
            X-Forwarded-Port: '{{ .Values.general.port }}'
            X-Forwarded-Proto: '{{ .Values.general.protocol }}'
        response:
          set:
            referrer-policy: no-referer-when-downgrade
      match:
        - uri:
            prefix: /ohien/connector-plugins/
        - uri:
            prefix: /ohien/connector-plugins
      rewrite:
        uri: /connector-plugins/
      route:
        - destination:
            host: 'ohien-kafka-connect'
            port:
              number: 8083
    - corsPolicy:
        allowHeaders:
          - x-requested-with
          - Content-Type
          - jwtheader
          - origin
          - authorization
          - accept
          - client-security-token
          - x-preserve-id
          - if-none-exist
          - prefer
          - referer
        allowMethods:
          - GET
          - POST
          - OPTIONS
          - PUT
          - DELETE
        allowOrigin:
          - '{{ .Values.general.protocol }}://{{ .Values.general.host }}'
      headers:
        request:
          set:
            X-Forwarded-Host: '{{ .Values.general.host }}'
            X-Forwarded-Port: '{{ .Values.general.port }}'
            X-Forwarded-Proto: '{{ .Values.general.protocol }}'
        response:
          set:
            referer-policy: no-referer-when-downgrade
      match:
        - uri:
            prefix: /ohien/
      route:
        - destination:
            host: 'ohien-control-panel'
            port:
              number: 8080
    - headers:
        response:
          set:
            referer-policy: no-referer-when-downgrade
      match:
        - uri:
            prefix: /ohien
      rewrite:
        uri: /ohien/
      route:
        - destination:
            host: 'ohien-control-panel'
            port:
              number: 8080
    - corsPolicy:
        allowHeaders:
          - x-requested-with
          - Content-Type
          - jwtheader
          - Origin
          - authorization
          - accept
          - client-security-token
          - x-preserve-id
          - if-none-exist
          - prefer
          - Referer
        allowMethods:
          - GET
          - POST
          - OPTIONS
          - PUT
          - DELETE
        allowOrigin:
          - '{{ .Values.general.protocol }}://{{ .Values.general.host }}'
        headers:
          request:
            remove:
              - authorization
        match:
          - uri:
              prefix: /kafka-schema-registry/
          - uri:
              prefix: /kafka-schema-registry
      rewrite:
        uri: /
      route:
        - destination:
            host: 'ohien-kafka-schema-registry'
            port:
              number: 8081
{{- end }}