apiVersion: apps/v1
kind: Deployment
metadata:
  name: 'ohien-control-panel'
  labels:
    app: 'ohien-control-panel'
spec:
  replicas: 0
  selector:
    matchLabels:
      app: 'ohien-control-panel'
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'false'
      labels:
        app: 'ohien-control-panel'
    spec:
      containers:
        - resources:
            limits:
              cpu: 150m
              memory: 1200Mi
            requests:
              cpu: 100m
              memory: 256Mi
          readinessProbe:
            httpGet: 
              path: /ohien/active/health/readiness
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 110
            periodSeconds: 30
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /ohien/active/health/liveness
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 110
            periodSeconds: 30
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: 'ohien-control-panel-backend'
          env:
            - name: TZ
              value: '{{ .Values.timezone }}'
            - name: JVM_OPTS
              value: >-
                -Xms200M -Xmx1100M -Xss180K -XX:-TieredCompilation
                -XX:+UseStringDeduplication -noverify
            - name: TIME_ZONE
              value: '{{ .Values.timezone }}'
            - name: ELASTICSEARCH_ENABLED
              value: '{{ .Values.elasticsearch.enabled }}'
            - name: ELASTICSEARCH_URL
              value: '{{ .Values.elasticsearch.host }}:{{ .Values.elasticsearch.port }}'
            - name: ELASTICSEARCH_HOST
              value: '{{ .Values.elasticsearch.host }}'
            - name: ELASTICSEARCH_PORT
              value: '{{ .Values.elasticsearch.port }}'
            - name: ELASTICSEARCH_TEMPLATE_PATH
              value: /app/resources/template.json
            - name: KUBERNETES_URL
              value: 'https://kubernetes.default'
            - name: KUBERNETES_NAMESPACE_PATH
              value: /var/run/secrets/kubernetes.io/serviceaccount/namespace
            - name: KUBERNETES_TOKEN_PATH
              value: /var/run/secrets/kubernetes.io/serviceaccount/token
            - name: SERVER_PORT
              value: '8081'
            - name: SERVER_MAXHTTPHEADSIZE
              value: 60KB
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: health
            - name: MANAGEMENT_ENDPOINT_HEALTH_GROUP_LIVENESS_INCLUDE
              value: livenessState
          ports:
            - containerPort: 8081
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /app/indrasalud-home/host.properties
              name: hnhome-host-props
              subPath: host.properties
            - mountPath: /app/indrasalud-home/iscore/conf/sso.properties
              name: hnhome-iscore-sso-props
              subPath: sso.properties
            - mountPath: /app/indrasalud-home/integration.properties
              name: hnhome-integration-props
              readOnly: true
              subPath: integration.properties
            - mountPath: /app/indrasalud-home/ohien/conf/logback-config.xml
              name: 'ohien-control-panel-backend-config'
              subPath: logback-config.xml
            - mountPath: /app/resources/template.json
              name: 'ohien-control-panel-backend-config'
              subPath: template.json
            - mountPath: /cert/cert-domain.crt
              name: cert-volume
              subPath: tls.crt
          terminationMessagePolicy: File
          image: '{{ .Values.registry.host }}/{{ .Values.registry.project }}/ohien-control-panel:{{ .Values.image.backend.tag }}'
        - image: '{{ .Values.registry.host }}/{{ .Values.registry.project }}/ohien-control-panel-frontend:{{ .Values.image.frontend.tag }}'
          imagePullPolicy: IfNotPresent
          name: 'ohien-control-panel-frontend'
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 412Mi
            requests:
              cpu: 50m
              memory: 200Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /usr/share/nginx/html/ohien/assets/config/env.json
              name: 'ohien-control-panel-frontend-config'
              subPath: env.json
            - mountPath: /usr/share/nginx/html/ohien/keycloak.json
              name: hnhome-ohsso-front
              readOnly: true
              subPath: keycloak.json
            - mountPath: /etc/nginx/nginx.conf
              name: nginx-front-cfg
              readOnly: true
              subPath: nginx.conf
            - mountPath: /usr/share/nginx/html/ohien/ohsso-lib/ohsso-lib.js
              name: ohsso-lib
              readOnly: true
              subPath: ohsso-lib.js
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: 'oh-docker-creds'
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccountName: 'ohien-control-panel'
      volumes:
        - configMap:
            defaultMode: 420
            items:
              - key: template.json
                path: template.json
              - key: logback-config.xml
                path: logback-config.xml
            name: 'ohien-control-panel-backend-config'
          name: 'ohien-control-panel-backend-config'
        - configMap:
            defaultMode: 420
            items:
              - key: env.json
                path: env.json
            name: 'ohien-control-panel-frontend-config'
          name: 'ohien-control-panel-frontend-config'
        - configMap:
            defaultMode: 420
            name: hnhome-ohsso-front
          name: hnhome-ohsso-front
        - configMap:
            defaultMode: 420
            name: nginx-front-cfg
          name: nginx-front-cfg
        - configMap:
            defaultMode: 420
            name: ohsso-lib
          name: ohsso-lib
        - configMap:
            defaultMode: 420
            name: hnhome-host-props
          name: hnhome-host-props
        - configMap:
            defaultMode: 420
            name: hnhome-iscore-sso-props
          name: hnhome-iscore-sso-props
        - configMap:
            defaultMode: 420
            name: hnhome-integration-props
          name: hnhome-integration-props
        - secret:
            secretName: cert-domain
          name: cert-volume
