apiVersion: v2
name: onesaithealthcare-ohhda-chart
description: Onesait Healthcare HDA chart for k8s
home: https://github.com/onesaithealthcare/onesaithealthcare-charts
type: application
version: "4.0.0"
appVersion: "4.6.0"
keywords:
  - Minsait
  - Onesait Healthcare
  - HDA
maintainers:
  - name: Onesait Healthcare
    email: soporteosh@indra.es
    url: 
icon: https://raw.githubusercontent.com/onesaitplatform/onesaitplatform-ce-charts/2.1.0-ce/images/onesaitplatform.png