kind: Deployment
apiVersion: apps/v1
metadata:
  name: '{{ .Values.ohhda.app.name }}'
  labels:
    app: '{{ .Values.ohhda.app.name }}'
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
  replicas: 1
  selector:
    matchLabels:
      app: '{{ .Values.ohhda.app.name }}'
  template:
    metadata:
      labels:
        app: '{{ .Values.ohhda.app.name }}'
      annotations:
        sidecar.istio.io/inject: 'false'
    spec:
      imagePullSecrets:
        - name: {{ .Values.global.docker.registry.secret }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - {{ .Values.ohhda.app.name }}
              topologyKey: kubernetes.io/hostname
      serviceAccountName: oh-module
      containers:
        - name: '{{ .Values.ohhda.app.name }}'
          image: >-
            {{ .Values.global.docker.registry.host }}/{{ .Values.global.docker.registry.project }}/ohhda-viewer:{{ .Values.ohhda.version.image_tag }}
          ports:
            - containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ohhda/index.html
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ohhda/index.html
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20
          volumeMounts:
            - name: '{{ .Values.ohhda.app.name }}-cfg'
              mountPath: /usr/share/nginx/html/ohhda/assets/config
              readOnly: true
            - name: '{{ .Values.ohhda.app.name }}-i18n'
              mountPath: /usr/share/nginx/html/ohhda/assets/i18n
              readOnly: true
            - name: hnhome-ohsso-front
              readOnly: true
              mountPath: /usr/share/nginx/html/ohhda/keycloak.json
              subPath: keycloak.json
            - name: nginx-front-cfg
              readOnly: true
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: ohsso-lib
              readOnly: true
              mountPath: /usr/share/nginx/html/ohhda/ohsso-lib.js
              subPath: ohsso-lib.js
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          imagePullPolicy: Always
      volumes:
        - name: '{{ .Values.ohhda.app.name }}-cfg'
          configMap:
            name: '{{ .Values.ohhda.app.name }}-cfg'
        - name: '{{ .Values.ohhda.app.name }}-i18n'
          configMap:
            name: '{{ .Values.ohhda.app.name }}-i18n'
        - name: hnhome-ohsso-front
          configMap:
            name: hnhome-ohsso-front
            defaultMode: 420
        - name: nginx-front-cfg
          configMap:
            name: nginx-front-cfg
            defaultMode: 420
        - name: ohsso-lib
          configMap:
            name: ohsso-lib
            defaultMode: 420