{{- if eq .Values.global.domain.gateway_type "istio"  }}
kind: VirtualService
apiVersion: networking.istio.io/v1beta1
metadata:
  name: '{{ .Values.ohhda.app.name }}-virtual-service'
spec:
  gateways:
    - {{ .Values.global.domain.gateway }}
  hosts:
    - '{{ .Values.global.domain.host }}'
  http:
    - headers:
        request:
          set:
            x-forwarded-host: '{{ .Values.global.domain.host }}'
            x-forwarded-port: '{{ .Values.global.domain.port }}'
            x-forwarded-proto: {{ .Values.global.domain.protocol }}
      match:
        - uri:
            prefix: /ohhda/
      route:
        - destination:
            host: '{{ .Values.ohhda.app.name }}'
            port:
              number: 8080
    - match:
        - uri:
            prefix: /ohhda/
      route:
        - destination:
            host: '{{ .Values.ohhda.app.name }}'
            port:
              number: 8080
    - match:
        - uri:
            exact: /ohhda
      rewrite:
        uri: /ohhda/
      route:
        - destination:
            host: '{{ .Values.ohhda.app.name }}'
            port:
              number: 8080
{{- end }}