{{- if eq .Values.global.domain.gateway-type "istio"  }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: '$ohcon-virtual-service'
spec:
  gateways:
    - oh-modules-gateway
  hosts:
    - '${GENERAL_HOST}'
  http:
    - headers:
        request:
          set:
            X-Forwarded-Host: '{{ .Values.global.domain.host }}'
            X-Forwarded-Port: '{{ if eq .Values.global.domain.protocol "http" }}80{{ else if eq .Values.global.domain.protocol "https" }}443{{ end }}'
            X-Forwarded-Proto: '{{ .Values.global.domain.protocol }}'
      match:
        - uri:
            prefix: /hnconf/fhir/
        - uri:
            prefix: /hnconf/configuration/
        - uri:
            exact: /hnconf/keycloak.json
        - uri:
            exact: /hnconf/healthcheck
      route:
        - destination:
            host: 'ohcon-back'
            port:
              number: 8080
    - match:
        - uri:
            prefix: /hnconf/
      route:
        - destination:
            host: 'ohcon-front'
            port:
              number: 8080
    - match:
        - uri:
            prefix: /hnconf
      rewrite:
        uri: /hnconf/
      route:
        - destination:
            host: 'ohcon-front'
            port:
              number: 8080
    - match:
        - uri:
            prefix: /ohconf-webcomponents/
      route:
        - destination:
            host: ohcon-webcomponents-front
            port:
              number: 8080
    - match:
        - uri:
            prefix: /ohconf/
      route:
        - destination:
            host: ohcon-ng15-front
            port:
              number: 8080
    - match:
        - uri:
            prefix: /ohconf
      rewrite:
        uri: /ohconf/
      route:
        - destination:
            host: ohcon-ng15-front
            port:
              number: 8080
{{- end }}