apiVersion: v1
kind: ConfigMap
metadata:
  name: 'ohcon-back-cfg'
data:
  ehcache.xml: >
    <?xml version="1.0" encoding="UTF-8"?>

    <ehcache name="hnconfCache"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="http://ehcache.org/ehcache.xsd">

    <defaultCache eternal="false" maxElementsInMemory="100"
      overflowToDisk="false" diskPersistent="false" timeToIdleSeconds="3600" 
      timeToLiveSeconds="14400" memoryStoreEvictionPolicy="LRU" />

    <cache name="propsLikeValueNameModuleCache"
      eternal="false"
      maxElementsInMemory="10"
      overflowToDisk="false"
      diskPersistent="false"
      timeToIdleSeconds="3600"
      timeToLiveSeconds="14400"
      memoryStoreEvictionPolicy="LRU" />

    <cache name="resolvedPropsByModuleCache"
      eternal="false"
      maxElementsInMemory="20"
      overflowToDisk="false"
      diskPersistent="false"
      timeToIdleSeconds="3600"
      timeToLiveSeconds="14400"
      memoryStoreEvictionPolicy="LRU" />
        
    <cache name="propsByModuleCache"
      eternal="false"
      maxElementsInMemory="20"
      overflowToDisk="false"
      diskPersistent="false"
      timeToIdleSeconds="3600"
      timeToLiveSeconds="14400"
      memoryStoreEvictionPolicy="LRU" />

    <cache name="propByIdCache"
      eternal="false"
      maxElementsInMemory="10"
      overflowToDisk="false"
      diskPersistent="false"
      timeToIdleSeconds="3600"
      timeToLiveSeconds="14400"
      memoryStoreEvictionPolicy="LRU" />

    <cache name="paramModuleFileCache"
      eternal="false"
      maxElementsInMemory="10"
      overflowToDisk="false"
      diskPersistent="false"
      timeToIdleSeconds="3600"
      timeToLiveSeconds="14400"
      memoryStoreEvictionPolicy="LRU" />

    <cache name="modulesListCache"
      eternal="false"
      maxElementsInMemory="10"
      overflowToDisk="false"
      diskPersistent="false"
      timeToIdleSeconds="3600"
      timeToLiveSeconds="14400"
      memoryStoreEvictionPolicy="LRU" />

    <cache name="filesListCache"
      eternal="false"
      maxElementsInMemory="10"
      overflowToDisk="false"
      diskPersistent="false"
      timeToIdleSeconds="3600"
      timeToLiveSeconds="14400"
      memoryStoreEvictionPolicy="LRU" />

    <cache name="fileByIdCache"
      eternal="false"
      maxElementsInMemory="10"
      overflowToDisk="false"
      diskPersistent="false"
      timeToIdleSeconds="3600"
      timeToLiveSeconds="14400"
      memoryStoreEvictionPolicy="LRU" />

    <cache name="fileModuleCache"
      eternal="false"
      maxElementsInMemory="10"
      overflowToDisk="false"
      diskPersistent="false"
      timeToIdleSeconds="3600"
      timeToLiveSeconds="14400"
      memoryStoreEvictionPolicy="LRU" />

    <cache name="fileModuleNameCache"
      eternal="false"
      maxElementsInMemory="10"
      overflowToDisk="false"
      diskPersistent="false"
      timeToIdleSeconds="3600"
      timeToLiveSeconds="14400"
      memoryStoreEvictionPolicy="LRU" />

    <cache name="paramsByModuleAndSectionCache"
      eternal="false"
      maxElementsInMemory="20"
      overflowToDisk="false"
      diskPersistent="false"
      timeToIdleSeconds="3600"
      timeToLiveSeconds="14400"
      memoryStoreEvictionPolicy="LRU" />
    </ehcache>  
  hnconf.properties: |
    datasource.hnconf=jdbc/hnconf
    defaultSchema.hnconf={{ .Values.ohcon.db.schema }}
    hibernate.transaction.flush_before_completion=true
    hibernate.current_session_context_class=jta
{{- if eq .Values.global.database.type "mysql" }}
    hibernate.dialect=org.hibernate.dialect.MySQLDialect
{{- else }}
    hibernate.dialect=org.hibernate.dialect.Oracle10gDialect
{{- end }}
    hibernate.jdbc.batch_size=25
    hibernate.jdbc.fetch_size=25
    hibernate.jdbc.batch_fetch_size=25
    datatableElementsByPageSearch=15
    datatableElementsByPageEdition=8
    database.selected={{ .Values.global.database.type }}
    maxElementsSelectAll=300
    #propiedades relacionadas con FHIR
    fhir.url.system=http://indra.hn.es/fhir/codesystems/
  logback-config.xml: |
    <included>
      <appender name="stdout" class="ch.qos.logback.core.ConsoleAppender">
        <layout class="ch.qos.logback.classic.PatternLayout">
          <pattern>[%d{dd/MM/yy HH:mm:ss.SSS}][%-5p][%C{0}.%M] %msg %n</pattern>
        </layout>
      </appender>
      <logger name="com.minsait.onesait" level="{{ if eq .Values.global.environment.type "dev" }}INFO{{ else if eq .Values.global.environment.type "prod" }}ERROR{{ end}}" />
      <logger name="es.indra.hn.hnconf" level="{{ if eq .Values.global.environment.type "dev" }}INFO{{ else if eq .Values.global.environment.type "prod" }}ERROR{{ end}}" />
      <logger name="org.springframework" level="{{ if eq .Values.global.environment.type "dev" }}INFO{{ else if eq .Values.global.environment.type "prod" }}ERROR{{ end}}" />
      <logger name="org.hibernate" level="{{ if eq .Values.global.environment.type "dev" }}INFO{{ else if eq .Values.global.environment.type "prod" }}ERROR{{ end}}" />
      <logger name="org.hibernate.SQL" level="{{ if eq .Values.global.environment.type "dev" }}INFO{{ else if eq .Values.global.environment.type "prod" }}ERROR{{ end}}" />
      <logger name="org.hibernate.type" level="{{ if eq .Values.global.environment.type "dev" }}INFO{{ else if eq .Values.global.environment.type "prod" }}ERROR{{ end}}" />
      <logger name="hnLoggable" level="INFO" />
      <root level="INFO">
        <appender-ref ref="stdout" />
      </root>  
    </included>
  persistence.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <persistence version="2.0"
      xmlns="http://java.sun.com/xml/ns/persistence" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://java.sun.com/xml/ns/persistence http://java.sun.com/xml/ns/persistence/persistence_2_0.xsd">
    <persistence-unit name="HNCONFPU" transaction-type="RESOURCE_LOCAL">
      <provider>org.hibernate.ejb.HibernatePersistence</provider>                  
        <!-- Mapping mysql identity --> 
        <mapping-file>META-INF/mysql-mapping.xml</mapping-file>
    </persistence-unit>
    </persistence>
