apiVersion: apps/v1
kind: Deployment
metadata:
  name: 'ohcon-back'
  labels:
    app: 'ohcon-back'
spec:
  replicas: {{ if eq .Values.global.environment.type "dev" }}1{{ else if eq .Values.global.environment.type "prod" }}2{{ end}}
  selector:
    matchLabels:
      app: 'ohcon-back'
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: 'ohcon-back'
      annotations:
        sidecar.istio.io/inject: 'false'
    spec:
      restartPolicy: Always
      serviceAccountName: oh-module
      imagePullSecrets:
        - name: 'oh-docker-creds'
      schedulerName: default-scheduler
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - ohcon-back
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 30
      securityContext: {}
      containers:
        - resources:
            limits:
              cpu: 300m
              memory: 1200Mi
            requests:
              cpu: 100m
              memory: 750Mi
          readinessProbe:
            httpGet:
              path: /hnconf/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 61
            timeoutSeconds: 1
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: 'ohcon-back'
          livenessProbe:
            httpGet:
              path: /hnconf/health/liveness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 120
            timeoutSeconds: 1
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 4
          env:
            - name: JVM_OPTS
              value: '-Dindrasalud.home=/hn_home -Xms256m -Xmx1024M'
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: ohcon-back-jetty-cfg
              readOnly: true
              mountPath: /var/lib/jetty/webapps/ROOT/WEB-INF/jetty-env.xml
              subPath: jetty-env.xml
            - name: ohcon-back-cfg
              readOnly: true
              mountPath: /hn_home/hnconf/conf
            - name: ohcon-back-host-props
              readOnly: true
              mountPath: /hn_home/host.properties
              subPath: host.properties
            - name: ohcon-back-integration-props
              readOnly: true
              mountPath: /hn_home/integration.properties
              subPath: integration.properties
            - name: ohcon-back-jms-props
              readOnly: true
              mountPath: /hn_home/jms.properties
              subPath: jms.properties
            - name: ohcon-back-iscore-sso-props
              readOnly: true
              mountPath: /hn_home/iscore/conf
            - name: cert-domain
              mountPath: /cert/cert-domain.crt
              subPath: tls.crt
          terminationMessagePolicy: File
          image: '{{ .Values.global.docker.registry.host }}/{{ .Values.global.docker.registry.project }}/ohcon-back@{{ .Values.onesaithealthcare-ohcon-chart.ohcon.sha256-back }}'
      serviceAccount: oh-module
      volumes:
        - name: ohcon-back-cfg
          configMap:
            name: ohcon-back-cfg
            defaultMode: 420
        - name: ohcon-back-jetty-cfg
          configMap:
            name: ohcon-back-jetty-cfg
            defaultMode: 420
        - name: ohcon-back-host-props
          configMap:
            name: hnhome-host-props
            defaultMode: 420
        - name: ohcon-back-integration-props
          configMap:
            name: hnhome-integration-props
            defaultMode: 420
        - name: ohcon-back-jms-props
          configMap:
            name: hnhome-jms-props
            defaultMode: 420
        - name: ohcon-back-iscore-sso-props
          configMap:
            name: hnhome-iscore-sso-props
            defaultMode: 420
        - name: cert-domain
          secret:
            secretName: cert-domain
            items:
              - key: tls.crt
                path: tls.crt
            defaultMode: 420
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
