{{- if eq .Values.global.domain.gateway_type "k8s_gateway"  }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ohcon-http-route
spec:
  hostnames:
    - {{ .Values.global.domain.host }}
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: oh-modules-gateway
      sectionName: oh-modules
  rules:
    - backendRefs:
        - group: ''
          kind: Service
          name: ohcon-back
          namespace: {{ .Release.Namespace }}
          port: 8080
          weight: 1
      filters:
        - requestHeaderModifier:
            set:
              - name: X-Forwarded-Host
                value: {{ .Values.global.domain.host }}
              - name: X-Forwarded-Proto
                value: {{ .Values.global.domain.protocol }}
              - name: X-Forwarded-Port
                value: '{{ if eq .Values.global.domain.protocol "http" }}80{{ else if eq .Values.global.domain.protocol "https" }}443{{ end }}'
          type: RequestHeaderModifier
      matches:
        - path:
            type: PathPrefix
            value: /hnconf/fhir/
        - path:
            type: PathPrefix
            value: /hnconf/configuration/
        - path:
            type: PathPrefix
            value: /hnconf/keycloak.json
        - path:
            type: PathPrefix
            value: /hnconf/healthcheck
    - backendRefs:
        - group: ''
          kind: Service
          name: ohcon-front
          namespace: {{ .Release.Namespace }}
          port: 8080
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /hnconf/
    - backendRefs:
        - group: ''
          kind: Service
          name: ohcon-front
          namespace: {{ .Release.Namespace }}
          port: 8080
          weight: 1
      matches:
        - path:
            type: Exact
            value: /hnconf
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplaceFullPath
              replaceFullPath: /hnconf/
    - backendRefs:
        - group: ''
          kind: Service
          name: ohcon-webcomponents-front
          namespace: {{ .Release.Namespace }}
          port: 8080
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /ohconf-webcomponents/
    - backendRefs:
        - group: ''
          kind: Service
          name: ohcon-ng15-front
          namespace: {{ .Release.Namespace }}
          port: 8080
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /ohconf/
{{- end }}
