enabled: true
ohatn:
  # image-version: 4.3.0
  sha256-front: sha256:b157b38c6ed98681e5040afe005ffad76035f16fb3b7dc24e55024074dc9b2ca
  sha256-back: sha256:f413c1e2626a4f29e4bfcb54f7fbe12fee91266472029d24d07e4161eadaae94
  db:
    schema: us_hnatna # usually the same as user
    user: us_hnatna
    pass: 
global:
  environment:
    type: dev # Opciones: dev, prod 
  domain:
    protocol: # Opciones: http, https
    host:
    gateway-type: # Opciones: istio, k8s-gateway
  database:
    type: mysql # Opciones: mysql, oracle
    host:
    port:
    oracle_sid: # only needed for Oracle
    oracle_partitioning: false # true|false, only needed for Oracle
    properties: # for example: ?serverTimezone=UTC
  docker:
    registry:
      host: docksdtr.indra.es
      project: multhn_cmhn20_2
