{{- if eq .Values.global.domain.gateway_type "k8s_gateway" }}
apiVersion: gateway.networking.k8s.io/v1
kind: CORS
metadata:
  name: ohprm-cors-policy
spec:
  allowOrigins:
    - {{ .Values.ohprm.app.url_prof_server }}
    - {{ .Values.ohprm.app.url_server }}
  allowMethods:
    - GET
    - POST
    - OPTIONS
    - PUT
    - DELETE
  allowHeaders:
    - x-requested-with
    - Content-Type
    - jwtheader
    - origin
    - authorization
    - accept
    - client-security-token
    - x-preserve-id
    - if-none-exist
    - prefer
    - referer
    - host
    - origin

kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: ohprm-http-route
spec:
  parentRefs:
    - name: {{ .Values.global.domain.gateway }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /ohprm/api/fhir/
        - path:
            type: Exact
            value: /ohprm/healthcheck
      filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            set:
              - name: X-Forwarded-Host
                value: {{ .Values.global.domain.host }}
              - name: X-Forwarded-Port
                value: '{{ if eq .Values.global.domain.protocol "http" }}80{{ else if eq .Values.global.domain.protocol "https" }}443{{ end }}'
              - name: X-Forwarded-Proto
                value: {{ .Values.global.domain.protocol }}
        - type: ExtensionRef
          extensionRef:
            group: gateway.networking.k8s.io
            kind: CORS
            name: ohprm-cors-policy
      backendRefs:
        - name: {{ .Values.ohprm.app.backend_app }}
          port: 8080
    - matches:
        - path:
            type: PathPrefix
            value: /ohprm/
      filters:
        - type: ExtensionRef
          extensionRef:
            group: gateway.networking.k8s.io
            kind: CORS
            name: ohprm-cors-policy
      backendRefs:
        - name: {{ .Values.ohprm.app.front_app }}
          port: 8080
    - matches:
        - path:
            type: PathPrefix
            value: /ohprm
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: PathPrefix
              replacePrefixMatch: /ohprm/
        - type: ExtensionRef
          extensionRef:
            group: gateway.networking.k8s.io
            kind: CORS
            name: ohprm-cors-policy
      backendRefs:
        - name: {{ .Values.ohprm.app.front_app }}
          port: 8080
{{- end }}