kind: ConfigMap
apiVersion: v1
metadata:
  name: ohmpi-front-cfg
data:
  env.json: |-
    {
        "hnconf_url": "{{ .Values.global.domain.protocol }}://{{ .Values.global.domain.host }}/hnconf",
        "isolated_module": "false",
        "read.external.patient.url": "{{ .Values.global.domain.protocol }}://{{ .Values.global.domain.host }}/fhir-out/Patient/",
        "keycloak-js-dist":"{{ .Values.global.domain.protocol }}://{{ .Values.global.domain.host }}/mpi/ohsso-lib.js",
        "app_theme":"./assets/css/themes/default"
    }   

  column-config.json: |-
    {
        "iconInfo": {
            "view": false
        },
        "name": {
            "view": true
        },
        "id": {
            "view": false
        },
        "age": {
            "view": false
        },
        "cipa": {
            "view": true,
            "system": "2.16.724.4.40.222"
        },
        "dniNie": {
            "label": "mpi.filter.dni",
            "view": true,
            "system": "112.111.124.222"
        },
        "phones": {
            "view": true
        },
        "identifier": {
            "view": false
        },
        "action": {
            "view": true
        }
    }        
   
  duplicate-column-config.json: |-
    {
      "name": {
          "view": true
      },
      "id": {
          "view": true
      },
      "age": {
          "view": true
      },
      "identifier": {
          "view": true
      },
      "action": {
          "view": true
      },
      "othersFhirpath": [
        {
          "label" : "mpi.filter.cipa",
          "attribute" : "cipa",
          "view" : false,
          "fhirpath": "Patient.identifier.where(system='2.16.724.4.40.222').value",
          "internalSearch": true,
          "confidential": true,
          "resultClass": "data-secondary data-document-value"
        },
        {
          "label" : "mpi.filter.dni",
          "attribute" : "dniNie",
          "view" : false,
          "fhirpath": "Patient.identifier.where(system='112.111.124.222').value",
          "internalSearch": true,
          "confidential": true,
          "resultClass": "data-secondary data-document-value"
        },
        {
          "label" : "mpi.filter.cip.autonomous",
          "attribute" : "cipAutonomous",
          "view" : false,
          "fhirpath": "Patient.identifier.where(system='2.16.724.4.40.222').value",
          "internalSearch": true,
          "confidential": true,
          "resultClass": "data-secondary data-document-value"
        },
        {
          "label" : "mpi.label.phone",
          "attribute" : "phones",
          "view" : false,
          "fhirpath": "{}.union(Patient.telecom.where(system='phone' or system='sms').value)",
          "internalSearch": true,
          "confidential": false
        },
        {
          "label" : "label.filter.passport",
          "attribute" : "passport",
          "view" : false,
          "fhirpath": "Patient.identifier.where(system='112.111.124.223').value",
          "internalSearch": true,
          "confidential": true,
          "resultClass": "data-secondary data-document-value"
        },
        {
          "label" : "mpi.label.info",
          "attribute" : "birthDate",
          "dataType": "DATE",
          "view" : false,
          "fhirpath": "Patient.birthDate",
          "internalSearch": true,
          "confidential": true
        }
      ]
    }    

  filter-config.json: |-
    {
        "code": {
            "render": true,
            "defaultValue": null
        },
        "status": {
            "render": true,
            "defaultValue": null
        },
        "name": {
            "render": false,
            "defaultValue": null
        },
        "birthdate": {
            "render": true,
            "defaultValue": null
        },
        "from_age": {
            "render": true,
            "defaultValue": null
        },
        "to_age": {
            "render": true,
            "defaultValue": null
        },
        "document_type": {
            "render": true,
            "defaultValue": null
        },
        "document_value": {
            "render": true,
            "defaultValue": null
        },
        "contact_type": {
            "render": true,
            "defaultValue": null
        },
        "contact_value": {
            "render": true,
            "defaultValue": null
        },
        "coverage_type": {
            "render": false,
            "defaultValue": null
        },
        "coverage_value": {
            "render": false,
            "defaultValue": null
        },
        "gender": {
            "render": true,
            "defaultValue": null
        },
        "given": {
            "render": true,
            "defaultValue": null
        },
        "family": {
            "render": true,
            "defaultValue": null
        },
        "cipa": {
            "render": true,
            "defaultValue": null,
            "system": "2.16.724.4.40.222"
        },
        "dniNie": {
            "label": "mpi.filter.dni",
            "render": true,
            "defaultValue": null,
            "system": "112.111.124.222"
        }
    }      

  nginx.conf: |-
     worker_processes  auto;
     error_log  /var/log/nginx/error.log notice;
     pid        /tmp/nginx.pid;
     
     events {
       worker_connections  1024;
     }
     http {
       proxy_temp_path /tmp/proxy_temp;
       client_body_temp_path /tmp/client_temp;
       fastcgi_temp_path /tmp/fastcgi_temp;
       uwsgi_temp_path /tmp/uwsgi_temp;
       scgi_temp_path /tmp/scgi_temp;
       include       /etc/nginx/mime.types;
       default_type  application/octet-stream;
       log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                       '$status $body_bytes_sent "$http_referer" '
                       '"$http_user_agent" "$http_x_forwarded_for"';
       access_log  /var/log/nginx/access.log  main;
       sendfile        on;
       #tcp_nopush     on;
       keepalive_timeout  65;
     
       gzip  on;
       gzip_disable "msie6";
       gzip_min_length 1100;
       gzip_buffers 16 8k;
       gzip_proxied any;
       gzip_types    text/plain application/javascript application/x-javascript text/javascript text/xml text/css;
     
       include /etc/nginx/conf.d/*.conf;
     }    
