apiVersion: v1
kind: ConfigMap
metadata:
  name: ohmpi-back-cfg
data:
  ehcache.xml: >
     <?xml version="1.0" encoding="UTF-8"?> 
     <ehcache name="ispobCache" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://ehcache.org/ehcache.xsd">
        <defaultCache eternal="false" maxElementsInMemory="100" overflowToDisk="false" diskPersistent="false" timeToIdleSeconds="7200" timeToLiveSeconds="21600" memoryStoreEvictionPolicy="LRU" />
        <cache name="CacheSrv_configParams" eternal="false" maxElementsInMemory="10"  overflowToDisk="false" diskPersistent="false" timeToIdleSeconds="7200" timeToLiveSeconds="21600" memoryStoreEvictionPolicy="LRU" />    
        <cache name="CacheSrv_configParamsNoTrad" eternal="false" maxElementsInMemory="1" overflowToDisk="false" diskPersistent="false" timeToIdleSeconds="7200" timeToLiveSeconds="21600" memoryStoreEvictionPolicy="LRU" />    
        <cache name="CacheSrv_traduccion" eternal="false" maxElementsInMemory="10" overflowToDisk="false" diskPersistent="false" timeToIdleSeconds="7200" timeToLiveSeconds="21600" memoryStoreEvictionPolicy="LRU" />    
        
        <cache name="CacheSrv_MetPersonNames" eternal="false" maxElementsInMemory="5" overflowToDisk="false" diskPersistent="false" timeToIdleSeconds="7200" timeToLiveSeconds="21600" memoryStoreEvictionPolicy="LRU" />
        <cache name="CacheSrv_CatContactTypes" eternal="false" maxElementsInMemory="5" overflowToDisk="false" diskPersistent="false" timeToIdleSeconds="7200" timeToLiveSeconds="21600" memoryStoreEvictionPolicy="LRU" />
        <cache name="CacheSrv_CatContactUses" eternal="false" maxElementsInMemory="5" overflowToDisk="false" diskPersistent="false" timeToIdleSeconds="7200" timeToLiveSeconds="21600" memoryStoreEvictionPolicy="LRU" />
        <cache name="CacheSrv_CatAddressTypes" eternal="false" maxElementsInMemory="5" overflowToDisk="false" diskPersistent="false" timeToIdleSeconds="7200" timeToLiveSeconds="21600" memoryStoreEvictionPolicy="LRU" />
        <cache name="CacheSrv_MetAddress" eternal="false" maxElementsInMemory="5" overflowToDisk="false" diskPersistent="false" timeToIdleSeconds="7200" timeToLiveSeconds="21600" memoryStoreEvictionPolicy="LRU" />
        <cache name="CacheSrv_CatFieldTypes" eternal="false" maxElementsInMemory="5" overflowToDisk="false" diskPersistent="false" timeToIdleSeconds="7200" timeToLiveSeconds="21600" memoryStoreEvictionPolicy="LRU" />
        <cache name="CacheSrv_CatAlphabets" eternal="false" maxElementsInMemory="5" overflowToDisk="false" diskPersistent="false" timeToIdleSeconds="7200" timeToLiveSeconds="21600" memoryStoreEvictionPolicy="LRU" />
        <cache name="CacheSrv_MetFieldAddByVisible" eternal="false" maxElementsInMemory="5" overflowToDisk="false" diskPersistent="false" timeToIdleSeconds="7200" timeToLiveSeconds="21600" memoryStoreEvictionPolicy="LRU" /> <cache name="CacheSrv_MetFieldAddBySection" eternal="false" maxElementsInMemory="30" overflowToDisk="false" diskPersistent="false" timeToIdleSeconds="7200" timeToLiveSeconds="21600" memoryStoreEvictionPolicy="LRU" /> <cache name="CacheSrv_MetFieldAddBySectionById" eternal="false" maxElementsInMemory="50" overflowToDisk="false" diskPersistent="false" timeToIdleSeconds="7200" timeToLiveSeconds="21600" memoryStoreEvictionPolicy="LRU" />
        <cache name="CacheSrv_MetDuplicityCriterias" eternal="false" maxElementsInMemory="5" overflowToDisk="false" diskPersistent="false" timeToIdleSeconds="7200" timeToLiveSeconds="21600" memoryStoreEvictionPolicy="LRU" />
        <cache name="CacheSrv_MetUnknownNames" eternal="false" maxElementsInMemory="5" overflowToDisk="false" diskPersistent="false" timeToIdleSeconds="7200" timeToLiveSeconds="21600" memoryStoreEvictionPolicy="LRU" />
        <cache name="CacheSrv_CatNameFieldTypes" eternal="false" maxElementsInMemory="5" overflowToDisk="false" diskPersistent="false" timeToIdleSeconds="7200" timeToLiveSeconds="21600" memoryStoreEvictionPolicy="LRU" />
        <cache name="CacheSrv_MetNewBorn" eternal="false" maxElementsInMemory="1" overflowToDisk="false" diskPersistent="false" timeToIdleSeconds="7200" timeToLiveSeconds="21600" memoryStoreEvictionPolicy="LRU" />
        <cache name="CacheSrv_MetNewBornName" eternal="false" maxElementsInMemory="1" overflowToDisk="false" diskPersistent="false" timeToIdleSeconds="7200" timeToLiveSeconds="21600" memoryStoreEvictionPolicy="LRU" />
        <cache name="CacheSrv_MetAssignmentConfig" eternal="false" maxElementsInMemory="1" overflowToDisk="false" diskPersistent="false" timeToIdleSeconds="7200" timeToLiveSeconds="21600" memoryStoreEvictionPolicy="LRU" />
        <cache name="CacheSrv_MetAssignmentRanges" eternal="false" maxElementsInMemory="1" overflowToDisk="false" diskPersistent="false" timeToIdleSeconds="7200" timeToLiveSeconds="21600" memoryStoreEvictionPolicy="LRU" />
        <cache name="CacheSrv_MetAssignmentTypes" eternal="false" maxElementsInMemory="1" overflowToDisk="false" diskPersistent="false" timeToIdleSeconds="7200" timeToLiveSeconds="21600" memoryStoreEvictionPolicy="LRU" /> <cache name="CacheSrv_MetAssignmentTypeById" eternal="false" maxElementsInMemory="20" overflowToDisk="false" diskPersistent="false" timeToIdleSeconds="7200" timeToLiveSeconds="21600" memoryStoreEvictionPolicy="LRU" />
        <cache name="CacheSrv_MetContactTypes" eternal="false" maxElementsInMemory="5" overflowToDisk="false" diskPersistent="false" timeToIdleSeconds="7200" timeToLiveSeconds="21600" memoryStoreEvictionPolicy="LRU" /> <cache name="CacheSrv_MetContactTypeByCode" eternal="false" maxElementsInMemory="20" overflowToDisk="false" diskPersistent="false" timeToIdleSeconds="7200" timeToLiveSeconds="21600" memoryStoreEvictionPolicy="LRU" />
        <cache name="CacheSrv_MetSections" eternal="false" maxElementsInMemory="30" overflowToDisk="false" diskPersistent="false" timeToIdleSeconds="7200" timeToLiveSeconds="21600" memoryStoreEvictionPolicy="LRU" /> <cache name="CacheSrv_sectionContainsAddFields" eternal="false" maxElementsInMemory="15" overflowToDisk="false" diskPersistent="false" timeToIdleSeconds="7200" timeToLiveSeconds="21600" memoryStoreEvictionPolicy="LRU" /> <cache name="CacheSrv_subsectionContainsAddFields" eternal="false" maxElementsInMemory="50" overflowToDisk="false" diskPersistent="false" timeToIdleSeconds="7200" timeToLiveSeconds="21600" memoryStoreEvictionPolicy="LRU" /> <cache name="hnconfCache_StringProperty" eternal="false" maxElementsInMemory="200" overflowToDisk="false" diskPersistent="false" timeToIdleSeconds="120" timeToLiveSeconds="120" memoryStoreEvictionPolicy="LRU" /> <cache name="hnconfCache_IntegerProperty" eternal="false" maxElementsInMemory="200" overflowToDisk="false" diskPersistent="false" timeToIdleSeconds="120" timeToLiveSeconds="120" memoryStoreEvictionPolicy="LRU" />  <cache name="CacheSrv_SearchParameter" eternal="false" maxElementsInMemory="200" overflowToDisk="false"
         diskPersistent="false" timeToIdleSeconds="7200" timeToLiveSeconds="21600" memoryStoreEvictionPolicy="LRU" /> 
     </ehcache>     

  ispob.properties: >
      ######## Config BD  ########
      
{{- if eq .Values.global.database.type "mysql" }}

      hibernate.dialect=org.hibernate.dialect.MySQLDialect
{{- else }}

      hibernate.dialect=org.hibernate.dialect.Oracle10gDialect
{{- end }}

      database.selected={{ .Values.global.database.type }}
      
      ######## Datasource ########
      
      datasource.ispob=ISPOB_DS
      
      defaultSchema.ispob={{ .Values.ohmpi.db.schema }}
      
      hibernate.jdbc.batch_size=50
     
      ######## Lucene ########
      
      hibernate.search.index.mode=lucene-disabled
      
      #[lucene-disabled|lucene-standalone|lucene-master|lucene-slave|lucene-infinispan]
      
      hibernate.search.default.sourceBase=${indrasalud.home}/ispob/lucene-master
      
      hibernate.search.default.indexBase=${indrasalud.home}/ispob/lucene
      
      hibernate.search.default.refresh=60
      
      
      ######## ActiveMQ ########
      
      activemq.enabled=false
      
      activemq.queue.hibernate_search=ISPOB.hibernateSearch
      
      activemq.topic.hnconf.param.clientId=ISPOB_HNCONF_PARAM
      
      activemq.topic.hnconf.param.subscriptionName=ISPOB_HNCONF_PARAM
      
      
      activemq.topic.hnaut.workplace.clientId=ISPOB_HNAUT_WORKPLACE
      
      activemq.topic.hnaut.workplace.subscriptionName=ISPOB_HNAUT_WORKPLACE
      
      activemq.topic.hnconf.identifier.clientId=ISPOB_HNCONF_IDENTIFIER
      
      activemq.topic.hnconf.identifier.subscriptionName=ISPOB_HNCONF_IDENTIFIER
      
      activemq.reconnect.interval.attempts=10000
      
      activemq.reconnect.max.attempts=10
      
      
      
      iframe_allowed_from=https://weblogic.proyvalhnwl1.indra.es
      
      logout.url=${keycloak.url}/realms/${keycloak.realm}/protocol/openid-connect/logout?redirect_uri=${hnpob.url}/sso/logout
      
     
      
      ###3 Numero de hebras para las notificaciones ##
      
      mpi.notification.num.threads=5 
      
      cache.type=ehcache
      
      liquibase.enable=true
      
      liquibase.context.partition.enable={{ .Values.global.database.oracle_partitioning }}
      

  hotrod-client.properties: >
      # Connection
      
      infinispan.client.hotrod.server_list=infinispan.oh-base.svc.cluster.local:11222
      
      # Client intelligence
      
      # External clients can use `BASIC` intelligence only.
      
      infinispan.client.hotrod.client_intelligence=BASIC
      
      # Authentication
      
      infinispan.client.hotrod.use_auth=true
      
      infinispan.client.hotrod.use_ssl=false
      
      # Application user credentials.
      
      # The default username is test.
      
      infinispan.client.hotrod.auth_username=test
      
      infinispan.client.hotrod.auth_password=changeit
      
      infinispan.client.hotrod.auth_server_name=infinispan
      
      infinispan.client.hotrod.sasl_properties.javax.security.sasl.credentials=true
      
      infinispan.client.hotrod.sasl_mechanism=DIGEST-MD5
      
      infinispan.client.hotrod.auth_realm=default
      
      infinispan.client.hotrod.socket_timeout=1000
      
      infinispan.client.hotrod.connect_timeout=1000
      
      infinispan.client.hotrod.max_retries=1
      
      # Encryption
      
      #infinispan.client.hotrod.sni_host_name=infinispan-app-hotrod-infinispan.apps.lab.openshift.com
      
      # Path to the TLS certificate.
      
      # Clients automatically generate trust stores from certificates.
      
      #infinispan.client.hotrod.trust_store_path=/opt/jboss/hn_home/ispob/conf/tls.crt
      
      ## Connection pooling configuration
      
      maxActive = -1
      
      maxIdle = -1
      
      whenExhaustedAction = 1
      
      minEvictableIdleTimeMillis=300000
      
      minIdle = 1
    
  logback-config.xml: |
      <?xml version="1.0" encoding="UTF-8"?>
      <included>
        <appender name="stdout" class="ch.qos.logback.core.ConsoleAppender">
          <layout class="ch.qos.logback.classic.PatternLayout">
            <pattern>[%d{dd/MM/yy HH:mm:ss.SSS}][%-5p][%C{0}.%M] %msg %n%rEx</pattern>
          </layout>
        </appender>      
        <logger name="hnLoggable" level="{{ if eq .Values.global.environment.type "dev" }}INFO{{ else if eq .Values.global.environment.type "prod" }}ERROR{{ end}}" />
        <logger name="hnAudit" level="{{ if eq .Values.global.environment.type "dev" }}INFO{{ else if eq .Values.global.environment.type "prod" }}ERROR{{ end}}" />
        <logger name="org.springframework.security" level="{{ if eq .Values.global.environment.type "dev" }}INFO{{ else if eq .Values.global.environment.type "prod" }}ERROR{{ end}}" />
        <logger name="es.indra.hn.keycloak" level="{{ if eq .Values.global.environment.type "dev" }}INFO{{ else if eq .Values.global.environment.type "prod" }}ERROR{{ end}}" />
        <logger name="org.keycloak.adapters" level="{{ if eq .Values.global.environment.type "dev" }}INFO{{ else if eq .Values.global.environment.type "prod" }}ERROR{{ end}}" />
        <logger name="org.springframework" level="{{ if eq .Values.global.environment.type "dev" }}INFO{{ else if eq .Values.global.environment.type "prod" }}ERROR{{ end}}" />
        <logger name="org.hibernate" level="{{ if eq .Values.global.environment.type "dev" }}INFO{{ else if eq .Values.global.environment.type "prod" }}ERROR{{ end}}" />
        <logger name="org.hibernate.SQL" level="{{ if eq .Values.global.environment.type "dev" }}INFO{{ else if eq .Values.global.environment.type "prod" }}ERROR{{ end}}"/>
        <logger name="org.hibernate.type" level="{{ if eq .Values.global.environment.type "dev" }}INFO{{ else if eq .Values.global.environment.type "prod" }}ERROR{{ end}}" />
        <logger name="ca.uhn.fhir.context" level="{{ if eq .Values.global.environment.type "dev" }}INFO{{ else if eq .Values.global.environment.type "prod" }}ERROR{{ end}}" />
        <logger name="org.apache" level="{{ if eq .Values.global.environment.type "dev" }}INFO{{ else if eq .Values.global.environment.type "prod" }}ERROR{{ end}}" />
        <logger name="es.indra.ihs" level="{{ if eq .Values.global.environment.type "dev" }}INFO{{ else if eq .Values.global.environment.type "prod" }}ERROR{{ end}}" />
        <logger name="es.indra.indrasalud" level="{{ if eq .Values.global.environment.type "dev" }}INFO{{ else if eq .Values.global.environment.type "prod" }}ERROR{{ end}}" />
        <logger name="es.indra.hn.ispob" level="{{ if eq .Values.global.environment.type "dev" }}INFO{{ else if eq .Values.global.environment.type "prod" }}ERROR{{ end}}" />
        <logger name="es.indra.hn.ispob.notification" level="{{ if eq .Values.global.environment.type "dev" }}INFO{{ else if eq .Values.global.environment.type "prod" }}ERROR{{ end}}" />
        <logger name="es.indra.hn.ispob.fhir.provider.impl" level="{{ if eq .Values.global.environment.type "dev" }}INFO{{ else if eq .Values.global.environment.type "prod" }}ERROR{{ end}}" />
        <logger name="es.indra.indrasalud.ispob" level="{{ if eq .Values.global.environment.type "dev" }}INFO{{ else if eq .Values.global.environment.type "prod" }}ERROR{{ end}}" />
        <logger name="es.indra.hn.plugins" level="{{ if eq .Values.global.environment.type "dev" }}INFO{{ else if eq .Values.global.environment.type "prod" }}ERROR{{ end}}" />
        <logger name="es.indra.hn.plugins.notification" level="{{ if eq .Values.global.environment.type "dev" }}INFO{{ else if eq .Values.global.environment.type "prod" }}ERROR{{ end}}" />
        <logger name="org.springframework" level="{{ if eq .Values.global.environment.type "dev" }}INFO{{ else if eq .Values.global.environment.type "prod" }}ERROR{{ end}}" />
        <logger name="org.springframework.scheduling" level="{{ if eq .Values.global.environment.type "dev" }}INFO{{ else if eq .Values.global.environment.type "prod" }}ERROR{{ end}}" />
        <logger name="org.quartz" level="{{ if eq .Values.global.environment.type "dev" }}INFO{{ else if eq .Values.global.environment.type "prod" }}ERROR{{ end}}" />
        <logger name="es.indra.ihs.iscore" level="{{ if eq .Values.global.environment.type "dev" }}INFO{{ else if eq .Values.global.environment.type "prod" }}ERROR{{ end}}" />
        <logger name="org.dozer" level="error" />
        <root level="INFO">
          <appender-ref ref="stdout" />
        </root>
      </included>


  plugin.properties: >
    # propiedades del plugin de desconocidos
    
    tipo.ciudadano.field.name=tipo_ciudadano
    
    tipo.ciudadano.no.identificable.code=PNI
    
    # propiedades del plugin de validacion del dni
    
    document.dni.system=112.111.124.222    
