kind: Deployment
apiVersion: apps/v1
metadata:
  name: ohmpi-front
  labels:
    app: ohmpi-front
spec:
  replicas: {{ if eq .Values.global.environment.type "dev" }}1{{ else if eq .Values.global.environment.type "prod" }}2{{ end}}
  selector:
    matchLabels:
      app: ohmpi-front
  template:
    metadata:
      labels:
        app: ohmpi-front
      annotations:
        sidecar.istio.io/inject: 'false'
    spec:
      restartPolicy: Always
      serviceAccountName: oh-module
      imagePullSecrets:
        - name: 'oh-docker-creds'
      schedulerName: default-scheduler
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - ohmpi-front
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 30
      securityContext: {}
      containers:
        - resources:
            limits:
              cpu: 50m
              memory: 48Mi
            requests:
              cpu: 25m
              memory: 16Mi
          readinessProbe:
            httpGet:
              path: /mpi/index.html
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 61
            timeoutSeconds: 1
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: ohmpi-front
          livenessProbe:
            httpGet:
              path: /mpi/index.html
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: ohmpi-front-cfg
              readOnly: true
              mountPath: /usr/share/nginx/html/mpi/assets/config
            - name: ohmpi-front-logo-onesait
              readOnly: true
              mountPath: /usr/share/nginx/html/mpi/logo_onesait_netwok.png
              subPath: logo_onesait_netwok.png
            - name: ohmpi-front-logo-onesait-healthcare
              readOnly: true
              mountPath: /usr/share/nginx/html/mpi/onesait_healthcare.svg
              subPath: onesait_healthcare.svg
            - name: hnhome-ohsso-front
              readOnly: true
              mountPath: /usr/share/nginx/html/mpi/keycloak.json
              subPath: keycloak.json
            - name: nginx-front-cfg
              readOnly: true
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: ohsso-lib
              readOnly: true
              mountPath: /usr/share/nginx/html/mpi/ohsso-lib.js
              subPath: ohsso-lib.js                                
          terminationMessagePolicy: File
          image: '{{ .Values.global.docker.registry.host }}/{{ .Values.global.docker.registry.project }}/ohmpi-front@{{ .Values.ohmpi.sha256_front }}'
      serviceAccount: oh-module
      volumes:
        - name: ohmpi-front-cfg
          configMap:
            name: ohmpi-front-cfg
            defaultMode: 420
        - name: ohmpi-front-logo-onesait
          configMap:
            name: ohmpi-front-logo-onesait
            defaultMode: 420
        - name: ohmpi-front-logo-onesait-healthcare
          configMap:
            name: ohmpi-front-logo-onesait-healthcare
            defaultMode: 420
        - name: hnhome-ohsso-front
          configMap:
            name: hnhome-ohsso-front
            defaultMode: 420
        - name: nginx-front-cfg
          configMap:
            name: nginx-front-cfg
            defaultMode: 420
        - name: ohsso-lib
          configMap:
            name: ohsso-lib
            defaultMode: 420
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
