{{- if eq .Values.global.domain.gateway_type "istio"  }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:   
  name: ohmpi-virtual-service
spec:
  gateways:
    - oh-modules-gateway
  hosts:
    - '*'
  http:
    - headers:
        request:
          set:
            X-Forwarded-Host: {{ .Values.global.domain.host }}
            X-Forwarded-Port: '{{ if eq .Values.global.domain.protocol "http" }}80{{ else if eq .Values.global.domain.protocol "https" }}443{{ end }}'
            X-Forwarded-Proto: {{ .Values.global.domain.protocol }}
      match:
        - uri:
            prefix: /ispob/
      route:
        - destination:
            host: ohmpi-back
            port:
              number: 8080
    - match:
        - uri:
            prefix: /mpi/
      route:
        - destination:
            host: ohmpi-front
            port:
              number: 8080
    - match:
        - uri:
            prefix: /mpi
      rewrite:
        uri: /mpi/
      route:
        - destination:
            host: ohmpi-front
            port:
              number: 8080
{{- end }}