{{- if .Values.domain.istio  }}
kind: VirtualService
apiVersion: networking.istio.io/v1beta1
metadata:
  name: ohprm-virtual-service
  namespace: {{ .Values.prm.app.namespace }}
spec:
  gateways:
    - oh-modules-gateway
  hosts:
    - '*'
  http:
    - corsPolicy:
        allowHeaders:
          - x-requested-with
          - Content-Type
          - jwtheader
          - origin
          - authorization
          - accept
          - client-security-token
          - x-preserve-id
          - if-none-exist
          - prefer
          - referer
          - host
          - origin
        allowMethods:
          - GET
          - POST
          - OPTIONS
          - PUT
          - DELETE
        allowOrigin:
          - {{ .Values.prm.app.url_prof_server }}
          - {{ .Values.prm.app.url_server }}
      headers:
        request:
          set:
            x-forwarded-host: {{ .Values.prm.app.namespace }}.apps.lab.openshift.com
            x-forwarded-port: '443'
            x-forwarded-proto: https
      match:
        - uri:
            prefix: /ohprm/api/fhir/
        - uri:
            exact: /ohprm/healthcheck
      route:
        - destination:
            host: {{ .Values.prm.app.backend_app }}
            port:
              number: 8080
    - corsPolicy:
        allowHeaders:
          - x-requested-with
          - Content-Type
          - jwtheader
          - origin
          - authorization
          - accept
          - client-security-token
          - x-preserve-id
          - if-none-exist
          - prefer
          - referer
          - host
          - origin
        allowMethods:
          - GET
          - POST
          - OPTIONS
          - PUT
          - DELETE
        allowOrigin:
          - {{ .Values.prm.app.url_prof_server }}
          - {{ .Values.prm.app.url_server }}
      match:
        - uri:
            prefix: /ohprm/
      route:
        - destination:
            host: {{ .Values.prm.app.front_app }}
            port:
              number: 8080
    - corsPolicy:
        allowHeaders:
          - x-requested-with
          - Content-Type
          - jwtheader
          - origin
          - authorization
          - accept
          - client-security-token
          - x-preserve-id
          - if-none-exist
          - prefer
          - referer
          - host
          - origin
        allowMethods:
          - GET
          - POST
          - OPTIONS
          - PUT
          - DELETE
        allowOrigin:
          - {{ .Values.prm.app.url_prof_server }}
          - {{ .Values.prm.app.url_server }}
      match:
        - uri:
            prefix: /ohprm
      rewrite:
        uri: /ohprm/
      route:
        - destination:
            host: {{ .Values.prm.app.front_app }}
            port:
              number: 8080
{{- end }}