kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.prm.app.front_app }}
  namespace: {{ .Values.prm.app.namespace }}
  labels:
    app: {{ .Values.prm.app.front_app }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.prm.app.front_app }}
  template:
    metadata:
      labels:
        app: {{ .Values.prm.app.front_app }}
      annotations:
        sidecar.istio.io/inject: 'false'
    spec:
      restartPolicy: Always    
      serviceAccountName: oh-module      
      imagePullSecrets:
        - name: {{ .Values.docker.registry.host }}      
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      securityContext: {}        
      containers:
        - resources:
            limits:
              cpu: 50m
              memory: 48Mi
            requests:
              cpu: 25m
              memory: 16Mi
          readinessProbe:
            httpGet:
              path: /ohprm/index.html
              port: 8080
              scheme: HTTP            
            initialDelaySeconds: 60
            timeoutSeconds: 1
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: {{ .Values.prm.app.front_app }}
          livenessProbe:
            httpGet:
              path: /ohprm/index.html
              port: 8080
            initialDelaySeconds: 20
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          ports:
            - containerPort: 8080
              protocol: TCP          
          imagePullPolicy: Always                    
          volumeMounts:
            - name: {{ .Values.prm.app.front_app }}-cfg
              mountPath: /usr/share/nginx/html/ohprm/assets/config
              readOnly: true              
            - name: {{ .Values.prm.app.front_app }}-i18n
              mountPath: /usr/share/nginx/html/ohprm/assets/i18n
              readOnly: true
            - name: hnhome-ohsso-front
              readOnly: true
              mountPath: /usr/share/nginx/html/ohprm/keycloak.json
              subPath: keycloak.json
            - name: nginx-front-cfg
              readOnly: true
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: ohsso-lib
              readOnly: true
              mountPath: /usr/share/nginx/html/ohprm/ohsso-lib.js
              subPath: ohsso-lib.js                
          terminationMessagePolicy: File              
          image: '{{ .Values.docker.registry.host }}/{{ .Values.docker.registry.project }}/ohprm-front:{{ .Values.prm.version.front_image_tag }}'              
      volumes:
        - name: {{ .Values.prm.app.front_app }}-cfg
          configMap:
            name: {{ .Values.prm.app.front_app }}-cfg
        - name: {{ .Values.prm.app.front_app }}-i18n
          configMap:
            name: {{ .Values.prm.app.front_app }}-i18n
        - name: hnhome-ohsso-front
          configMap:
            name: hnhome-ohsso-front
            defaultMode: 420
        - name: nginx-front-cfg
          configMap:
            name: nginx-front-cfg
            defaultMode: 420
        - name: ohsso-lib
          configMap:
            name: ohsso-lib
            defaultMode: 420
      dnsPolicy: ClusterFirst            
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600      
