ohsso:
  # image-version: 4.10.0.oracle, 4.10.0.mysql
  sha256_oracle: sha256:c3dfdf3303fa75df3fcc3b605d380b07efa21c0be5be576036b6cad8ff31b059v
  sha256_mysql: sha256:c00d633e6ead0e9b73d3325714e968bbe75402b32f943c8265bcdc728a9ee512
  db:
    adminpassword:
    schema: us_ohsso # usually the same as user
    user: us_ohsso
    pass: 
global:
  environment:
    type: dev # Opciones: dev, prod 
  domain:
    protocol: # Opciones: http, https
    host:
    gateway_type: # Opciones: istio, k8s_gateway
  database:
    type: mysql # Opciones: mysql, oracle
    host:
    port:
    oracle_sid: # only needed for Oracle
    oracle_partitioning: false # true|false, only needed for Oracle
    properties: # for example: ?serverTimezone=UTC
  docker:
    registry:
      host: docksdtr.indra.es
      project: multhn_cmhn20_2

