kind: Service
apiVersion: v1
metadata:
  name: ohgeneric-form-webcomponents-front
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: ohgeneric-form-webcomponents-front
