kind: Deployment
apiVersion: apps/v1
metadata:
  name: ohgeneric-form-webcomponents-front
  labels:
    app: ohgeneric-form-webcomponents-front
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
  replicas: {{ if eq .Values.global.environment.type "dev" }}1{{ else if eq .Values.global.environment.type "prod" }}2{{ end}}
  selector:
    matchLabels:
      app: ohgeneric-form-webcomponents-front
  template:
    metadata:
      labels:
        app: ohgeneric-form-webcomponents-front
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      imagePullSecrets:
        - name: 'oh-docker-creds'
      serviceAccountName: oh-module
      containers:
        - name: ohgeneric-form-webcomponents-front
          image: {{ .Values.global.docker.registry.host }}/{{ .Values.global.docker.registry.project }}/ohgeneric-form-webcomponents@{{ .Values.ohwcform.sha256_front }}
          ports:
            - containerPort: 8080
              protocol: TCP

          livenessProbe:
            httpGet:
              path: /ohgeneric-form-webcomponents/remoteEntry.js
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /ohgeneric-form-webcomponents/remoteEntry.js
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20

          volumeMounts:
            - name: nginx-front-cfg
              readOnly: true
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf

            - name: nginx-front-cfg
              readOnly: true
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf

          resources:
            limits:
              cpu: 50m
              memory: 48Mi
            requests:
              cpu: 25m
              memory: 16Mi
          imagePullPolicy: Always

      volumes:
        - name: nginx-front-cfg
          configMap:
            name: nginx-front-cfg
            defaultMode: 420
