apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-01-10T09:11:55Z"
  name: alert-module
  namespace: oh-modules
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: alert-module
  sessionAffinity: None
  type: ClusterIP
