apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2024-12-19T16:42:37Z"
  labels:
    app: ohcmc-rulechain-front
  name: ohcmc-rulechain-front
  namespace: oh-modules
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ohcmc-rulechain-front
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      creationTimestamp: null
      labels:
        app: ohcmc-rulechain-front
    spec:
      containers:
        - image: {{ .Values.docker.registry.host }}/{{ .Values.docker.registry.project }}/ohcmc-thingsboard-front:{{ .Values.cmc.front_rulechain.image.tag }}
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /ohcmc-thingsboard/index.html
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: ohcmc-rulechain-front
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /ohcmc-thingsboard/index.html
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 50m
              memory: 48Mi
            requests:
              cpu: 25m
              memory: 16Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /usr/share/nginx/html/ohcmc-thingsboard/assets/config
              name: ohcmc-rulechain-front-cfg
              readOnly: true
            - mountPath: /usr/share/nginx/html/ohcmc-thingsboard/keycloak.json
              name: ohcmc-front-keycloak-cfg
              readOnly: true
              subPath: keycloak.json
            - mountPath: /etc/nginx/nginx.conf
              name: nginx-front-cfg
              readOnly: true
              subPath: nginx.conf
            - mountPath: /usr/share/nginx/html/ohcmc-thingsboard/ohsso-lib.js
              name: ohsso-lib
              readOnly: true
              subPath: ohsso-lib.js
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: {{ .Values.docker.registry.secret }}
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: oh-module
      serviceAccountName: oh-module
      terminationGracePeriodSeconds: 22
      volumes:
        - configMap:
            defaultMode: 420
            name: ohcmc-rulechain-front-cfg
          name: ohcmc-rulechain-front-cfg
        - configMap:
            defaultMode: 420
            name: ohcmc-front-keycloak-cfg
          name: ohcmc-front-keycloak-cfg
        - configMap:
            defaultMode: 420
            name: nginx-front-cfg
          name: nginx-front-cfg
        - configMap:
            defaultMode: 420
            name: ohsso-lib
          name: ohsso-lib
