apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ohcmc-front
  name: ohcmc-front
spec:
  progressDeadlineSeconds: 600
  replicas: {{ if eq .Values.environment.type "dev" }}1{{ else if eq .Values.environment.type "prod" }}2{{ end}}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ohcmc-front
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      creationTimestamp: null
      labels:
        app: ohcmc-front
    spec:
      containers:
        - image: {{ .Values.docker.registry.host }}/{{ .Values.docker.registry.project }}/ohcmc-front:{{ .Chart.AppVersion }}
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /ohcmc/index.html
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: ohcmc-front
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /ohcmc/index.html
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 50m
              memory: 48Mi
            requests:
              cpu: 25m
              memory: 16Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /usr/share/nginx/html/ohcmc/assets/config
              name: ohcmc-front-cfg
              readOnly: true
            - mountPath: /usr/share/nginx/html/ohcmc-dashboard/assets/config
              name: ohcmc-dashboard-front-cfg
              readOnly: true
            - mountPath: /usr/share/nginx/html/ohcmc/keycloak.json
              name: ohcmc-front-keycloak-cfg
              readOnly: true
              subPath: keycloak.json
            - name: ohcmc-dashboard-keycloak-cfg
              readOnly: true
              mountPath: /usr/share/nginx/html/ohcmc-dashboard/keycloak.json
              subPath: keycloak.json                
            - mountPath: /etc/nginx/nginx.conf
              name: nginx-front-cfg
              readOnly: true
              subPath: nginx.conf
            - mountPath: /usr/share/nginx/html/ohcmc/ohsso-lib.js
              name: ohsso-lib
              readOnly: true
              subPath: ohsso-lib.js
            - name: ohsso-lib-dashboard
              readOnly: true
              mountPath: /usr/share/nginx/html/ohcmc-dashboard/ohsso-lib.js
              subPath: ohsso-lib.js
              
              
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: 'oh-docker-creds'
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: oh-module
      serviceAccountName: oh-module
      terminationGracePeriodSeconds: 20
      volumes:
        - configMap:
            defaultMode: 420
            name: ohcmc-front-cfg
          name: ohcmc-front-cfg
        - name: ohcmc-dashboard-front-cfg
          configMap:
            name: ohcmc-dashboard-front-cfg
        - configMap:
            defaultMode: 420
            name: ohcmc-front-keycloak-cfg
          name: ohcmc-front-keycloak-cfg
        - name: ohcmc-dashboard-keycloak-cfg
          configMap:
            name: ohcmc-front-keycloak-cfg
            defaultMode: 420
        - configMap:
            defaultMode: 420
            name: nginx-front-cfg
          name: nginx-front-cfg
        - configMap:
            defaultMode: 420
            name: ohsso-lib
          name: ohsso-lib
