{{- if eq .Values.domain.gateway_type "istio"  }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: rule-engine-virtual-service-oh-mod
spec:
  gateways:
    - oh-modules-gateway
  hosts:
    - '*'
  http:
    - headers:
        response:
          set:
            Referrer-Policy: origin
      match:
        - uri:
            prefix: /rule-engine/
      rewrite:
        uri: /
      route:
        - destination:
            host: rule-engine-back
            port:
              number: 8080
{{- end }}              