apiVersion: v1
kind: ConfigMap
metadata:
  name: ohcmc-front-keycloak-cfg
data:
  keycloak.json: |-
    {
      "realm": "oh-base",
      "resource": "ruleengine",
      "public-client": true,
      "auth-server-url": "{{ .Values.domain.protocol }}://{{ .Values.domain.host }}/auth",
      "enable-cors": true
    }
