apiVersion: v1
data:
  conf: |
    export JAVA_OPTS="$JAVA_OPTS -Dplatform=deb -Dinstall.data_dir=/rule_engine/data"
    export JAVA_OPTS="$JAVA_OPTS -Xlog:gc*,heap*,age*,safepoint=debug:file=/var/log/rule_engine/${TB_SERVICE_ID}-gc.log:time,uptime,level,tags:filecount=10,filesize=10M"
    export JAVA_OPTS="$JAVA_OPTS -XX:+IgnoreUnrecognizedVMOptions -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/var/log/rule_engine/${TB_SERVICE_ID}-heapdump.bin"
    export JAVA_OPTS="$JAVA_OPTS -XX:-UseBiasedLocking -XX:+UseTLAB -XX:+ResizeTLAB -XX:+PerfDisableSharedMem -XX:+UseCondCardMark"
    export JAVA_OPTS="$JAVA_OPTS -XX:+UseG1GC -XX:MaxGCPauseMillis=500 -XX:+UseStringDeduplication -XX:+ParallelRefProcEnabled -XX:MaxTenuringThreshold=10"
    export JAVA_OPTS="$JAVA_OPTS -XX:+ExitOnOutOfMemoryError"
    export LOG_FILENAME=rule_engine.out
    export LOADER_PATH=/rule_engine/conf,/rule_engine/extensions
  logback: |
    <!DOCTYPE configuration>
    <configuration scan="false">

        <!-- appender name="fileLogAppender"
                  class="ch.qos.logback.core.rolling.RollingFileAppender">
            <file>/var/log/thingsboard/${TB_SERVICE_ID}/thingsboard.log</file>
            <rollingPolicy
                    class="ch.qos.logback.core.rolling.SizeAndTimeBasedRollingPolicy">
                <fileNamePattern>/var/log/thingsboard/${TB_SERVICE_ID}/thingsboard.%d{yyyy-MM-dd}.%i.log</fileNamePattern>
                <maxFileSize>100MB</maxFileSize>
                <maxHistory>30</maxHistory>
                <totalSizeCap>3GB</totalSizeCap>
            </rollingPolicy>
            <encoder>
                <pattern>%d{ISO8601} [%thread] %-5level %logger{36} - %msg%n</pattern>
            </encoder>
        </appender -->

        <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
            <encoder>
                <pattern>%d{ISO8601} [%thread] %-5level %logger{36} - %msg%n</pattern>
            </encoder>
        </appender>

        <logger name="com" level="ERROR" />
        <logger name="com.google.common.util.concurrent.AggregateFuture" level="OFF" />

        <logger name="org" level="ERROR" />
        <logger name="org.thingsboard" level="{{ if eq .Values.environment.type "dev" }}INFO{{ else if eq .Values.environment.type "prod" }}ERROR{{ end}}" />
        <logger name="org.springframework" level="WARN" />
        <logger name="org.hibernate" level="WARN" />

        <logger name="org.thingsboard.rule.engine.action" level="{{ if eq .Values.environment.type "dev" }}DEBUG{{ else if eq .Values.environment.type "prod" }}ERROR{{ end}}" />
        <logger name="com.minsait" level="{{ if eq .Values.environment.type "dev" }}DEBUG{{ else if eq .Values.environment.type "prod" }}ERROR{{ end}}" />
        <logger name="es.indra" level="{{ if eq .Values.environment.type "dev" }}DEBUG{{ else if eq .Values.environment.type "prod" }}ERROR{{ end}}" />
        <logger name="org.thingsboard.server.common.transport.service" level="{{ if eq .Values.environment.type "dev" }}DEBUG{{ else if eq .Values.environment.type "prod" }}ERROR{{ end}}" />

        <root level="{{ if eq .Values.environment.type "dev" }}INFO{{ else if eq .Values.environment.type "prod" }}ERROR{{ end}}">
            <!-- appender-ref ref="fileLogAppender"/ -->
            <appender-ref ref="STDOUT"/>
        </root>

    </configuration>
kind: ConfigMap
metadata:
  labels:
    name: rule-engine-config
  name: rule-engine-config
  namespace: oh-modules
