apiVersion: v1
kind: ConfigMap
metadata:
  name: ohcmc-front-cfg
data:
  env.json: |-
    {
        "hnconf_url": "{{ .Values.domain.protocol }}://{{ .Values.domain.host }}/hnconf",
        "keycloak-js-dist": "{{ .Values.domain.protocol }}://{{ .Values.domain.host }}/ohcmc/ohsso-lib.js"
    }

