apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    name: rule-engine-mongodb-config
  name: rule-engine-mongodb-config
data:
  ERROR_WAITING_TIME: "2000"
  MONGODB_CONNECTION_STRING: {{ .Values.cmc.database.mongodb }}
  MONGODB_DATABASE: {{ .Values.cmc.database.mongodb.dbname }}
