kind: ConfigMap
apiVersion: v1
metadata:
  name: restheart
data:
  rho: >-
    /mclient/connection-string->"{{ .Values.cmc.database.mongodb.connection_string }}";/http-listener/host->"0.0.0.0";/fullAuthorizer/enabled->true;/fullAuthorizer/authentication-required->false;/mongo/mongo-mounts[1]->{"where": "/", "what": "{{ .Values.cmc.database.mongodb.dbname }}"}
