apiVersion: v1
kind: ConfigMap
metadata:
  name: hnhome-iscore-sso-props
data:
  sso.properties: |-
    application.url=${${component.name}.url}
    
    general.url=${general.protocol}://${general.hostname}
    
    hnaut.context=hnaut
    
    hnaut.url=${general.url}/${hnaut.context}
    
    hncat.context=hncat
    
    hncat.url=${general.url}/${hncat.context}
    
    hnhos.context=ishos
    
    hnpob.context=ispob
    
    hnalert.context=hnalert
    
    hnalert.url=${general.url}/${hnalert.context}
      
    hncit.context=hncit
    
    hncit.url=${general.url}/${hncit.context}
    
    hnpob.url=${general.url}/${hnpob.context}
    
    hnrep.context=hnrep
    
    hnrep.url=${general.url}/${hnrep.context}
    
    hntri.context=hntri
    
    hntri.url=${general.url}/${hntri.context}
    
    hnurg.context=isurg
          
    iscit.context=iscit
    
    ISCIT.url=${general.url}/${iscit.context}
    
    isdes.context=desktop
    
    isdes.url=${general.url}/${isdes.context}
    
    ishos.context=ishos
    
    ishos.url=${general.url}/${ishos.context}
    
    ispob.context=ispob
    
    ispob.url=${general.url}/${ispob.context}
    
    isqui.context=isqui
    
    isqui.url=${general.url}/${isqui.context}
    
    issso.context=login
    
    issso.url=${general.url}/${issso.context}
    
    isurg.context=isurg
    
    isurg.url=${general.url}/${isurg.context}
    
    isvac.context=isvac
    
    isvac.url=${general.url}/${isvac.context}
    
    hnconf.context=hnconf
    
    hnconf.url=${general.url}/${hnconf.context}
    
    hncard.context=hncard
    
    hncard.url=${general.url}/${hncard.context}
    
    hngep.context=hngep
    
    hnprefac.context=hnprefac
    
    hnprefac.url=${general.url}/${hnprefac.context}
    
    hndoc.context=hndocService
    
    hndoc.url=${general.url}/${hndoc.context}
    
    hncli.context=hncliService
    
    hncli.url=${general.url}/${hncli.context}
    
    dsforms.context=dsforms
    
    dsforms.url=${general.url}/${dsforms.context}
    
    ohale.context=ohale
    
    ohale.url=${general.url}/${ohale.context}
    
    keycloak.client=hn-install
    
    keycloak.context=auth
    
    keycloak.realm=oh-base
    
    keycloak.context.redirect=auth/realms/${keycloak.realm}/redirect
    
    keycloak.disable_trust_manager=true
    
    keycloak.ssl_required=none
    
    keycloak.url={{ .Values.global.domain.protocol }}://{{ .Values.global.domain.host }}/${keycloak.context}
    
    keycloak.url.initial=${keycloak.url}/realms/${keycloak.realm}/protocol/openid-connect/token
    
    keycloak.url.redirect={{ .Values.global.domain.protocol }}://{{ .Values.global.domain.host }}/${keycloak.context.redirect}
    
    # keycloak.user=usuario1
    
    # keycloak.pass=????
    
    keycloak.login.client_id=ohsso
    
    keycloak.login.client_secret=NnI1R01TM3pFZmh1VHd2VzJnR0hDTUdZbG03VmsxVW8=
    
    keycloak.token.minimum.time.to.live=300
    
    mirth.context=hnint
