apiVersion: v1
kind: ConfigMap
metadata:
  name: hnhome-ohsso-front
data:
  keycloak.json: |-
    {
      "realm" : "oh-base",
      "resource" : "hnrole",
      "public-client": true,
      "auth-server-url": "{{ .Values.global.domain.protocol }}://{{ .Values.global.domain.host }}/auth",
      "enable-cors": true
    }
