{{- if .Values.global.docker.use.default_oh_registry }}
kind: Secret
apiVersion: v1
metadata:
  name: oh-docker-creds
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6eyJkb2Nrc2R0ci5pbmRyYS5lcyI6eyJ1c2VybmFtZSI6InJvYm90bXVsdGhuX2NtaG4yMF8yK29wZW5zaGlmdF9kZXYyIiwicGFzc3dvcmQiOiI3V05ENFBSZzNQelFxOUt2c2FBY1czdTFRbW1URUZoRiIsImF1dGgiOiJjbTlpYjNSdGRXeDBhRzVmWTIxb2JqSXdYeklyYjNCbGJuTm9hV1owWDJSbGRqSTZOMWRPUkRSUVVtY3pVSHBSY1RsTGRuTmhRV05YTTNVeFVXMXRWRVZHYUVZPSJ9fX0=
type: kubernetes.io/dockerconfigjson
{{- end }}