apiVersion: v1
kind: ConfigMap
metadata:
  name: 'ohsso-configmap-global'
data:
  keycloak.conf: >
    # build
    db={{ .Values.database.type }}
    http-enabled=true
    health-enabled=true
    http-relative-path=auth
    # cache=local|ispn 
    cache=ispn
    cache-stack=kubernetes
    # cache-config-file=cache-kubernetes.xml
    features=scripts
    metrics-enabled=true
    # run
    hostname=${GENERAL_HOST}
    proxy=passthrough
    http-port=8080
    {{- if eq .Values.database.type "mysql" }}
    db-url={{ .Values.database.mysql.url }}:us_keycloak{{ .Values.database.mysql.properties }}
    {{- else if eq .Values.database.type "oracle" }}
    db-url={{ .Values.database.oracle.url }}{{ .Values.database.oracle.properties }}
    {{- end }}
    db-username=us_keycloak
    db-password=us_keycloak
    log=console
    log-level=INFO,es.indra:INFO,com.minsait:INFO
    spi-login-protocol-openid-connect-legacy-logout-redirect-uri=true
    spi-user-storage-provider-timeout=12000