kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.ohcsm.app.back_name }}-jetty-cfg
data:
  jetty-env.xml: |
    <?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "configure_9_0.dtd">
    <Configure id="wac" class="org.eclipse.jetty.webapp.WebAppContext">
      <Set name="contextPath">/ohcsm</Set>
      <New class="org.eclipse.jetty.server.HttpConfiguration" id="httpConfig">
        <Set name="secureScheme">https</Set>
        <Set name="outputBufferSize">64768</Set>
        <Set name="requestHeaderSize">64192</Set>
        <Set name="responseHeaderSize">64192</Set>
        <Set name="sendServerVersion">true</Set>
        <Set name="sendDateHeader">false</Set>
        <Set name="headerCacheSize">512</Set>
      </New>
      <Get name="server" id="server">
        <Set name="connectors">
          <Array type="org.eclipse.jetty.server.ServerConnector">
            <Item>
              <New class="org.eclipse.jetty.server.ServerConnector">
                <Arg name="server">
                  <Ref refid="server" />
                </Arg>
                <Arg name="factories">
                  <Array type="org.eclipse.jetty.server.ConnectionFactory">
                    <Item>
                      <New class="org.eclipse.jetty.server.HttpConnectionFactory">
                        <Arg name="config">
                          <Ref refid="httpConfig" />
                        </Arg>
                      </New>
                    </Item>
                  </Array>
                </Arg>
                <Set name="port">8080</Set>
                <Set name="idleTimeout">30000</Set>
              </New>
            </Item>
          </Array>
        </Set>
      </Get>

      <!-- BD Entorno release-->
      <New id="ohcsmDS" class="org.eclipse.jetty.plus.jndi.Resource">
        <Arg></Arg>
        <Arg>jdbc/ohcsm</Arg>
        <Arg>
          <New class="org.apache.commons.dbcp.BasicDataSource">
            <Set name="driverClassName">{{ .Values.ohcsm.database.driver }}</Set>
            <Set name="url">{{ .Values.ohcsm.database.url }}</Set>
            <Set name="username">{{ .Values.ohcsm.database.user }}</Set>
            <Set name="password">{{ .Values.ohcsm.database.pass }}</Set>
            <Set name="validationQuery">SELECT 1 FROM DUAL</Set>
            <Set name="connectionProperties">oracle.jdbc.defaultLobPrefetchSize=-1</Set>
          </New>
        </Arg>
      </New>
    </Configure>
