kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.ohcsm.app.front_name }}-keycloak
data:
  keycloak-prof.json: |-
    {
      "realm" : "openshift-dev",
      "resource" : "hnrole",
      "public-client": true,
      "auth-server-url": "https://{{ .Values.global.domain.host }}/auth",
      "enable-cors": true
    }
  keycloak.json: |-
    {
      "realm" : "openshift-dev",
      "resource" : "ohpatient-light",
      "public-client": true,
      "auth-server-url": "https://{{ .Values.global.domain.host }}/auth",
      "enable-cors": true
    }
