{{- if eq .Values.domain.istio  }}
kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: {{ .Values.bpm.app.name }}-virtual-service
spec:
  gateways:
    - {{ .Values.bpm.app.gateway }}
  hosts:
    - '{{ .Values.bpm.app.host }}'
  http:
    - match:
        - uri:
            prefix: /ohbpm/assets/config
        - uri:
            prefix: /ohbpm/assets/css
      route:
        - destination:
            host: ohbpm-front
            port:
              number: 8080
    - match:
      - uri:
          prefix: /ohbpm/api
      - uri:
          prefix: /ohbpm/app
      - uri:
          prefix: /ohbpm/assets
      - uri:
          prefix: /ohbpm/lib
      headers:
        request:
          set:
            X-Forwarded-Host: {{ .Values.bpm.app.host }}
            X-Forwarded-Port: '443'
            X-Forwarded-Proto: https
      route:
        - destination:
            host: {{ .Values.bpm.app.name }}-back
            port:
              number: 8080
    - match:
        - uri:
            prefix: /ohbpm-smart/
      route:
        - destination:
            host: {{ .Values.bpm.app.name }}-smart-front
            port:
              number: 8080
    - match:
        - uri:
            prefix: /ohbpm-smart
      rewrite:
        uri: /ohbpm-smart/ 
      route:
        - destination:
            host: {{ .Values.bpm.app.name }}-smart-front
            port:
              number: 8080
    - match:
        - uri:
            prefix: /ohbpm-designer/
      route:
        - destination:
            host: {{ .Values.bpm.app.name }}-designer-front
            port:
              number: 8080
    - match:
        - uri:
            prefix: /ohbpm-designer
      rewrite:
        uri: /ohbpm-designer/ 
      route:
        - destination:
            host: {{ .Values.bpm.app.name }}-designer-front
            port:
              number: 8080
    - match:
        - uri:
            prefix: /ohbpm-prof/
      route:
        - destination:
            host: {{ .Values.bpm.app.name }}-prof-front
            port:
              number: 8080
    - match:
        - uri:
            prefix: /ohbpm-prof
      rewrite:
        uri: /ohbpm-prof/ 
      route:
        - destination:
            host: {{ .Values.bpm.app.name }}-prof-front
            port:
              number: 8080
    - match:
        - uri:
            prefix: /ohbpm-webcomponents
      route:
        - destination:
            host: {{ .Values.bpm.app.name }}-webcomponents-front
            port:
              number: 8080
    - match:
        - uri:
            prefix: /ohbpm/
      route:
        - destination:
            host: {{ .Values.bpm.app.name }}-front
            port:
              number: 8080
    - match:
        - uri:
            prefix: /ohbpm
      rewrite:
        uri: /ohbpm/ 
      route:
        - destination:
            host: {{ .Values.bpm.app.name }}-front
            port:
              number: 8080
{{- end }}
