kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.bpm.app.name }}-back-jetty
data:
  jetty-env.xml: |
    <?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "configure_9_0.dtd">
    <Configure id="wac" class="org.eclipse.jetty.webapp.WebAppContext">
      <Set name="contextPath">/ohbpm</Set>
      <New class="org.eclipse.jetty.server.HttpConfiguration" id="httpConfig">
        <Set name="secureScheme">https</Set>
        <Set name="outputBufferSize">64768</Set>
        <Set name="requestHeaderSize">64192</Set>
        <Set name="responseHeaderSize">64192</Set>
        <Set name="sendServerVersion">true</Set>
        <Set name="sendDateHeader">false</Set>
        <Set name="headerCacheSize">512</Set>
      </New>
      <Get name="server" id="server">
        <Set name="connectors">
          <Array type="org.eclipse.jetty.server.ServerConnector">
            <Item>
              <New class="org.eclipse.jetty.server.ServerConnector">
                <Arg name="server"><Ref refid="server" /></Arg>
                <Arg name="factories">
                  <Array type="org.eclipse.jetty.server.ConnectionFactory">
                    <Item>
                      <New class="org.eclipse.jetty.server.HttpConnectionFactory">
                        <Arg name="config"><Ref refid="httpConfig" /></Arg>
                      </New>
                    </Item>
                  </Array>
                </Arg>
                <Set name="port">8080</Set>
                <Set name="idleTimeout">30000</Set>
              </New>
            </Item>
          </Array>
        </Set>
      </Get>
      <New id="myMedCdrDS" class="org.eclipse.jetty.plus.jndi.Resource">
        <Arg></Arg>
        <Arg>jdbc/ohbpm</Arg>
        <Arg>
          <New class="com.zaxxer.hikari.HikariDataSource">
            <Arg>
              <New class="com.zaxxer.hikari.HikariConfig">
                  <Set name="maximumPoolSize">{{ .Values.bpm.database.max_pool_size }}</Set><!-- Ajusta segun tu carga -->
                  <Set name="minimumIdle">{{ .Values.bpm.database.min_idle }}</Set><!-- Mantén 10 conexiones activas para alta demanda -->
                  <Set name="connectionTimeout">{{ .Values.bpm.database.con_timeout }}</Set><!-- 30 segundos antes de lanzar excepcion si no hay conexiones -->
                  <Set name="idleTimeout">{{ .Values.bpm.database.idle_timeout }}</Set><!-- 10 minutos de inactividad antes de cerrar una conexión inactiva -->
                  <Set name="maxLifetime">{{ .Values.bpm.database.max_lifetime }}</Set><!-- 30 minutos máximo de vida por conexión -->
                  <Set name="validationTimeout">{{ .Values.bpm.database.val_timeout }}</Set><!-- Validar conexiones en 5 segundos -->
                  <Set name="leakDetectionThreshold">{{ .Values.bpm.database.leak_detection }}</Set><!-- Detectar conexiones colgadas después de 15 segundos -->
                  <Set name="driverClassName">{{ .Values.bpm.database.driver }}</Set>
                  <Set name="jdbcUrl">{{ .Values.bpm.database.url }}</Set>
                  <Set name="username">{{ .Values.bpm.database.user }}</Set>
                  <Set name="password">{{ .Values.bpm.database.pass }}</Set>
                  <Set name="connectionTestQuery">SELECT 1 FROM DUAL</Set><!-- Oracle específico para validar conexión -->
                  <Call name="addDataSourceProperty">
                      <Arg>oracle.jdbc.defaultLobPrefetchSize</Arg>
                      <Arg>-1</Arg>
                  </Call>
              </New>
            </Arg>
          </New>
        </Arg>
      </New>
    </Configure>
