kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.bpm.app.name }}-back
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: '9093'
    prometheus.io/scrape: 'true'
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: prom
      protocol: TCP
      port: 9093
      targetPort: 9093
  selector:
    app: {{ .Values.bpm.app.name }}-back
