kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.bpm.app.name }}-designer-front-i18n
data:
  es.json: |-
    {
      "ohbpm.label.title": "Título",
      "ohbpm.label.type": "Tipo",
      "ohbpm.label.lastUpdated": "Fecha",
      "ohbpm.label.confirm": "Confirmar",
      "ohbpm.label.create": "Crear",
      "ohbpm.label.discard": "Descartar",
      "ohbpm.label.description": "Descripción",
      "ohbpm.label.id": "Id",
      "ohbpm.label.new": "Nueva",
      "ohbpm.label.import": "Importar",
      "ohbpm.label.type.recommendation": "Recomendación",
      "ohbpm.label.type.questionnaire": "Cuestionarios y Escalas",
      "ohbpm.label.type.goal": "Indicadores",
      "ohbpm.label.type.patient.functional.valuation": "Valoración Funcional",
      "ohbpm.label.type.measurement": "Medición",
      "ohbpm.label.type.lab.test": "Pruebas de Laboratorio",
      "ohbpm.label.type.intervention": "Intervención",
      "ohbpm.label.type.care.plan": "Plan de cuidados",
      "ohbpm.label.type.social.plan": "Plan social",
      "ohbpm.label.type.therapeutic.plan": "Plan terapéutico",
      "ohbpm.label.type.reminder": "Recordatorio",
      "ohbpm.label.type.patient.or.care.giver": "Paciente / Cuidador",
      "ohbpm.message.update.activity.definition": "La activity definition {{value1}} se ha editado correctamente",
      "ohbpm.message.update.plan.definition": "El plan definition {{value1}} se ha editado correctamente",
      "ohbpm.message.activity.definition.success.title": "Activity Definition",
      "ohbpm.message.plan.definition.success.title": "Plan Definition",
      "ohbpm.message.error.format": "Error en el formateo del JSON",
      "ohbpm.message.error.format.title": "Error JSON",
      "ohbpm.message.delete": "El id {{value1}} se ha eliminado correctamente",
      "ohbpm.message.new": "Se ha creado correctamente",
      "ohbpm.message.import": "Se ha importado correctamente",
      "ohbpm.confirm.delete": "¿Está seguro que desea eliminar {{value1}}?",
      "label.delete": "Eliminar",
      "label.access.to.detail": "Acceder al detalle",
      "hnworklist.paginator.of": "de",
      "label.menu.dynamic.activities": "Actividades dinamicas",
      "label.menu.timers": "Temporizadores",
      "label.menu.incidents": "Incidencias"
    }

  
  en.json: |-
    {
      "ohbpm.label.title": "Title",
      "ohbpm.label.type": "Type",
      "ohbpm.label.lastUpdated": "Date",
      "ohbpm.label.confirm": "Confirm",
      "ohbpm.label.create": "Create",
      "ohbpm.label.discard": "Discard",
      "ohbpm.label.description": "Description",
      "ohbpm.label.id": "Id",
      "ohbpm.label.new": "New",
      "ohbpm.label.import": "Import",
      "ohbpm.label.type.recommendation": "Recommendation",
      "ohbpm.label.type.questionnaire": "Questionnaires and Scales",
      "ohbpm.label.type.goal": "Indicators",
      "ohbpm.label.type.patient.functional.valuation": "Functional Valuation",
      "ohbpm.label.type.measurement": "Measurement",
      "ohbpm.label.type.lab.test": "Lab Tests",
      "ohbpm.label.type.intervention": "Intervention",
      "ohbpm.label.type.care.plan": "Care Plan",
      "ohbpm.label.type.social.plan": "Social Plan",
      "ohbpm.label.type.therapeutic.plan": "Therapeutic Plan",
      "ohbpm.label.type.reminder": "Reminder",
      "ohbpm.label.type.patient.or.care.giver": "Patient / Caregiver",  
      "ohbpm.message.update.activity.definition": "The activity definition {{value1}} has been successfully edited.",
      "ohbpm.message.update.plan.definition": "The plan definition {{value1}} has been successfully edited",
      "ohbpm.message.activity.definition.success.title": "Activity Definition",
      "ohbpm.message.plan.definition.success.title": "Plan Definition",
      "ohbpm.message.error.format": "Error in JSON formatting",
      "ohbpm.message.error.format.title": "JSON error",
      "ohbpm.message.delete": "Id {{value1}} has been deleted successfully",
      "ohbpm.message.new": "It has been created successfully",
      "ohbpm.message.import": "It has been imported successfully",
      "ohbpm.confirm.delete": "Are you sure you want to delete {{value1}}?",
      "label.delete": "Delete",
      "label.access.to.detail": "Access to detail",
      "hnworklist.paginator.of": "of",
      "label.menu.dynamic.activities": "Dynamic activities",
      "label.menu.timers": "Timers",
      "label.menu.incidents": "Incidents"
    } 
