{{- if .Values.domain.istio }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: ohcmc-virtual-service
  namespace: oh-modules
spec:
  gateways:
    - oh-modules-gateway
  hosts:
    - '*'
  http:
    - match:
        - uri:
            prefix: /ohcmc-thingsboard/api/
      rewrite:
        uri: /api/
      route:
        - destination:
            host: rule-engine-back
            port:
              number: 8080
    - headers:
        response:
          set:
            Cache-Control: public, max-age=31536000
      match:
        - uri:
            regex: \/ohcmc-thingsboard\/(.*)\.js
      route:
        - destination:
            host: ohcmc-rulechain-front
            port:
              number: 8080
    - match:
        - uri:
            prefix: /ohcmc-thingsboard/
      route:
        - destination:
            host: ohcmc-rulechain-front
            port:
              number: 8080
    - match:
        - uri:
            prefix: /ohcmc-thingsboard
      rewrite:
        uri: /ohcmc-thingsboard/
      route:
        - destination:
            host: ohcmc-rulechain-front
            port:
              number: 8080
    - match:
        - uri:
            prefix: /ohcmc/
      route:
        - destination:
            host: ohcmc-front
            port:
              number: 8080
    - match:
        - uri:
            prefix: /ohcmc
      rewrite:
        uri: /ohcmc/
      route:
        - destination:
            host: ohcmc-front
            port:
              number: 8080
{{- end }}              