kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.hdr.app.name }}-back-jetty
data:
  jetty-env.xml: |
    <?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE Configure    PUBLIC "-//Jetty//Configure//EN" "configure_9_0.dtd">
    <Configure id="wac" class="org.eclipse.jetty.webapp.WebAppContext">
      <Get name="systemClasspathPattern">
        <Call name="add"><Arg>-javax.mail.</Arg></Call>
      </Get>
      <Get name="serverClasspathPattern">
        <Call name="add"><Arg>javax.mail.</Arg></Call>
      </Get>      
      <Set name="contextPath">/ehrserver</Set>
      <New class="org.eclipse.jetty.server.HttpConfiguration" id="httpConfig">
        <Set name="secureScheme">https</Set>
        <Set name="outputBufferSize">64768</Set>
        <Set name="requestHeaderSize">64192</Set>
        <Set name="responseHeaderSize">64192</Set>
        <Set name="sendServerVersion">true</Set>
        <Set name="sendDateHeader">false</Set>
        <Set name="headerCacheSize">512</Set>
      </New>
      <Get name="server" id="server">
        <Set name="connectors">
          <Array type="org.eclipse.jetty.server.ServerConnector">
            <Item>
              <New class="org.eclipse.jetty.server.ServerConnector">
                <Arg name="server"><Ref refid="server" /></Arg>
                <Arg name="factories">
                  <Array type="org.eclipse.jetty.server.ConnectionFactory">
                    <Item>
                      <New class="org.eclipse.jetty.server.HttpConnectionFactory">
                        <Arg name="config"><Ref refid="httpConfig" /></Arg>
                      </New>
                    </Item>
                  </Array>
                </Arg>
                <Set name="port">8080</Set>
                <Set name="idleTimeout">30000</Set>
              </New>
            </Item>
          </Array>
        </Set>
      </Get>
      <New id="myMedCdrDS" class="org.eclipse.jetty.plus.jndi.Resource">
        <Arg></Arg>
        <Arg>jdbc/myMedCdrDS</Arg>
        <Arg>
          <New class="org.apache.commons.dbcp2.BasicDataSource">
            <Set name="driverClassName">{{ .Values.hdr.database.driver }}</Set>
            <Set name="url">{{ .Values.hdr.database.url }}</Set>
            <Set name="username">{{ .Values.hdr.database.user }}</Set>
            <Set name="password">{{ .Values.hdr.database.pass }}</Set>
            <Set name="validationQuery">SELECT 1 FROM DUAL</Set>
            <Set name="initialSize">{{ .Values.hdr.database.initial_size }}</Set>
            <Set name="maxTotal">{{ .Values.hdr.database.max_total }}</Set>
            <Set name="connectionProperties">{{ .Values.hdr.database.connection_properties }}</Set>
          </New>
        </Arg>
      </New>
    </Configure>
