{{- if eq .Values.domain.gateway_type "istio"  }}
kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: {{ .Values.hdr.app.name }}-virtual-service
spec:
  gateways:
    - {{ .Values.hdr.app.gateway }}
  hosts:
    - '{{ .Values.domain.host }}'
  http:
    - headers:
        request:
          set:
            X-Forwarded-Host: {{ .Values.domain.host }}
            X-Forwarded-Port: '{{ .Values.domain.port }}'
            X-Forwarded-Proto: {{ .Values.domain.protocol }}
      match:
        - uri:
            prefix: /ehrserver/
      route:
        - destination:
            host: {{ .Values.hdr.app.name }}-back
            port:
              number: 8080
{{- end }}