kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.gen.app.name_back }}
  labels:
    app: {{ .Values.gen.app.name_back }}
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: prom
      protocol: TCP
      port: 9093
      targetPort: 9093
  selector:
    app: {{ .Values.gen.app.name_back }}
