gateway_type: # istio|k8s_gateway
host_oh_modules:
prot_oh_modules: 
namespace_oh_modules: oh-modules
ohsso:
  enabled: true
  url: 
  realm: oh-base
  client_id: oh-monitoring
  client_secret: 
prometheus:
  replicas: 1
  config_reloader_version: v0.80.1  
  kafka_namespace: oh-kafka
  oh_modules_namespace: oh-modules
  prometheus_version: v3.2.1
  oauth2_proxy_version: v7.8.1
  persistence:
    enabled: false
    size: 50Gi
    storageclass: 
grafana:
  grafana_version: 11.5.2
  admin_user: admin
  admin_pass: grafana
  