prometheus:
  replicas: 1
  host: testtemplate-prometheus.apps.lab.openshift.com
  config_reloader_version: v0.80.1
  prometheus_version: v3.2.1
  persistence:
    enabled: false
    size: 50Gi
    storageclass: 
  ohsso:
    enabled: true
    oauth2_proxy_version: v7.1.2
    url: https://oh-modules.apps.lab.openshift.com/auth/realms/openshift-dev/protocol/openid-connect/auth
    client_id: grafana
    client_secret: M7YRJSeUb4LRKF4jtL8iUMDBkHRueKUY
    
    