prometheus:
  replicas: 1
  host: testtemplate-prometheus.apps.lab.openshift.com
  config_reloader_version: v0.80.1
  kafka_namespace: oh-kafka
  oh_modules_namespace: oh-modules
  prometheus_version: v3.2.1
  persistence:
    enabled: false
    size: 50Gi
    storageclass: 
  ohsso:
    enabled: true
    oauth2_proxy_version: v7.1.2
    url: https://oh-modules.apps.lab.openshift.com/auth/realms/openshift-dev
    client_id: oh-monitoring
    client_secret: 
grafana:
  replicas: 1
  host: testtemplate-grafana.apps.lab.openshift.com
  grafana_version: v4.0