global:
  environment:
    type: dev # Opciones: dev, prod 
  domain:
    protocol: # Opciones: http, https
    host:
    gateway_type: # Opciones: istio, k8s_gateway
  database:
    type: mysql # Opciones: mysql, oracle
    host:
    port:
    oracle_sid: '' # only needed for Oracle
    oracle_partitioning: false # true|false, only needed for Oracle
    props: '' # for example: ?serverTimezone=UTC
  docker:
    registry:
      host: docksdtr.indra.es
      project: multhn_cmhn20_2
  host_alias:
    enabled: false
    ip: 
onesaithealthcare_ohsso_chart:
  ohsso:
    # image-version: 4.10.0.oracle, 4.10.0.mysql
    sha256_oracle: sha256:c3dfdf3303fa75df3fcc3b605d380b07efa21c0be5be576036b6cad8ff31b059v
    sha256_mysql: sha256:c00d633e6ead0e9b73d3325714e968bbe75402b32f943c8265bcdc728a9ee512
    db:
      adminpassword:
      schema: us_ohsso # usually the same as user
      user: us_ohsso
      pass: 
onesaithealthcare_ohcon_chart:
  ohcon:
    # image-version: 4.7.0
    sha256_front: sha256:b5a4c74477e085f165d3df970aaa240f1c795c6ba3ff4c2fe50d3521dad0857a
    sha256_front_ng15: sha256:197b7d19daf5710cdb6a2be628d8968ad13dacd3b84e7ba5642a2f660bbdbf86
    sha256_front_webc: sha256:f83c05c8fb34fec3e3ca75439afb816cbf5a89261c0e10576bd95514a5afd054
    sha256_back: sha256:16ff665be6424f41e4f265ec56a235f040e592d8ec5451d5e1262d447248d813
    db:
      schema: us_hnconf # usually the same as user
      user: us_hnconf
      pass: 
onesaithealthcare_ohaut_chart:
  ohaut:
    # image-version: 4.8.0
    sha256_front: sha256:93f0e09aa47ca2bb4ab36c687565688cde8f6310d006951e122611eeb6f85897
    sha256_back: sha256:ec2c915c8d11a6088e95646115123d5da4cf6f8efd5a9e5ae6a645f625f0172f
    db:
      schema: us_hnaut # usually the same as user
      user: us_hnaut
      pass: 
onesaithealthcare_ohont_chart:
  ohont:
    # image-version: 4.6.0
    sha256_front: sha256:e779cb92f8cacbb0b16872ba559e0fe2eadff8d4b658fe89bd3d6d642a4b2252
    sha256_back: sha256:c56d7656edf04dd6ff6e4178ded98d5d830c7d746a41a0b9e0ab1f991d537b4a
    db:
      schema: us_hncat # usually the same as user
      user: us_hncat
      pass: 
onesaithealthcare_ohmpi_chart:
  ohmpi:
    # image-version: 4.10.0
    sha256_front: sha256:28e1d41290aafe8f3d1f698ff04ec7d264e5b14a2c8448e6820452df1208a6f1
    sha256_back: sha256:57d0025179c491489fbfb71664652e584334fe4e61e8d3f8c1d4dba26b799f6c
    db:
      schema: us_hnpob # usually the same as user
      user: us_hnpob
      pass: 
  
onesaithealthcare_ohatn_chart:
  enabled: true
  ohatn:
    # image-version: 4.3.0
    sha256_front: sha256:b157b38c6ed98681e5040afe005ffad76035f16fb3b7dc24e55024074dc9b2ca
    sha256_back: sha256:f413c1e2626a4f29e4bfcb54f7fbe12fee91266472029d24d07e4161eadaae94
    db:
      schema: us_hnatna # usually the same as user
      user: us_hnatna
      pass: 
