global:
  environment:
    type: dev # Opciones: dev, prod 
  domain:
    protocol: # Opciones: http, https
    host:
    gateway_type: # Opciones: istio, k8s_gateway
  database:
    type: mysql # Opciones: mysql, oracle
    host:
    port:
    oracle_sid: '' # only needed for Oracle
    oracle_partitioning: false # true|false, only needed for Oracle
    props: '' # for example: ?serverTimezone=UTC
  docker:
    registry:
      host: docksdtr.indra.es
      project: multhn_cmhn20_2
  host_alias:
    enabled: false
    ip: 
onesaithealthcare_ohsso_chart:
  ohsso:
    image_tag_oracle: 4.10.0.oracle
    image_tag_mysql: 4.10.0.mysql
    db:
      adminpassword:
      schema: us_ohsso # usually the same as user
      user: us_ohsso
      pass: 
onesaithealthcare_ohcon_chart:
  ohcon:
    image_tag_front: 4.7.0
    image_tag_front_ng15: 4.7.0
    image_tag_front_webc: 4.7.0
    image_tag_back: 4.7.0
    db:
      schema: us_hnconf # usually the same as user
      user: us_hnconf
      pass: 
onesaithealthcare_ohaut_chart:
  ohaut:
    image_tag_front: 4.8.0
    image_tag_back: 4.8.0
    image_tag_front_wcint: 4.7.0
    db:
      schema: us_hnaut # usually the same as user
      user: us_hnaut
      pass: 
onesaithealthcare_ohont_chart:
  ohont:
    image_tag_front: 4.6.0
    image_tag_back: 4.6.0
    db:
      schema: us_hncat # usually the same as user
      user: us_hncat
      pass: 
onesaithealthcare_ohmpi_chart:
  ohmpi:
    image_tag_front: 4.10.0
    image_tag_back: 4.10.0
    db:
      schema: us_hnpob # usually the same as user
      user: us_hnpob
      pass: 
  
onesaithealthcare_ohatn_chart:
  ohatn:
    image_tag_front: 4.3.0
    image_tag_back: 4.3.0
    db:
      schema: us_hnatna # usually the same as user
      user: us_hnatna
      pass: 

onesaithealthcare_ohwcform_chart:
  ohwcform:
    image_tag_front: 4.9.0
onesaithealthcare_ohwcviewer_chart:
  ohwcviewer:
    image_tag_front: 4.6.0
onesaithealthcare_ohdsk_chart:
  ohdsk:
    image_tag_front: 3.23.0


