ohsso:
  enabled: true
environment:
  type: dev # Opciones: dev, prod 
domain:
  protocol: # Opciones: http, https
  host:
  istio: false
database:
  type: mysql # Opciones: mysql, oracle
  mysql:
    url: 
    properties: ?serverTimezone=UTC
  oracle:
    url:
    properties:
docker:
  registry:
    host: docksdtr.indra.es
    project: multhn_cmhn20_2
