{{- if not .Values.ohsso.enabled }}
kind: Secret
apiVersion: v1
metadata:
  name: grafana
data:
  admin-password: {{ .Values.grafana.admin_pass | b64enc }}
  admin-user: {{ .Values.grafana.admin_user | b64enc }}
  ldap-toml: ''
type: Opaque
{{- end }}