kind: Service
apiVersion: v1
metadata:
  name: grafana-service
spec:
  ipFamilies:
    - IPv4
  ports:
    - name: grafana-http
      protocol: TCP
      port: 3000
      targetPort: grafana-http
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: oh-grafana
