kind: ConfigMap
apiVersion: v1
metadata:
  name: grafana
data:
  grafana.ini: |
    [analytics]
    check_for_updates=false
    reporting_enabled=false
    check_for_plugin_updates=false
    
    [grafana_com]
    url = https://grafana.net
    
    [log]
    mode = console
    level = info
    
    [paths]
    data = /var/lib/grafana/
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    
{{- if .Values.ohsso.enabled }}    
    [auth]
    disable_signout_menu = true
    
    [auth.anonymous]
    enabled = false
    
    [auth.generic_oauth]
    auto_login = true
    api_url={{ .Values.ohsso.url }}/protocol/openid-connect/userinfo
    auth_url={{ .Values.ohsso.url }}/protocol/openid-connect/auth
    client_id={{ .Values.ohsso.client_id }}
    client_secret={{ .Values.ohsso.client_secret }}
    email_attribute_path = preferred_username
    enabled=true
    name=OHSSO
    role_attribute_path=contains(realm_access.roles[*], 'OHIEN_MONITORING') && 'Admin' || 'Viewer'
    role_attribute_strict= null
    scopes=openid email
    tls_skip_verify_insecure = true
    token_url={{ .Values.ohsso.url }}/protocol/openid-connect/token
{{- end }}
    
    [security]
    disable_initial_admin_creation={{ if .Values.ohsso.enabled }}true{{ else }}false{{ end}}
    allow_embedding = true
    cookie_samesite = lax
    cookie_secure = true
    
    [server]
    root_url={{ .Values.grafana.protocol }}://{{ .Values.grafana.host }}/grafana
    domian={{ .Values.grafana.host }}
    serve_from_sub_path=true
    
    [users]
    allow_sign_up={{ if .Values.ohsso.enabled }}false{{ else }}true{{ end}}