kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: oh-grafana
  annotations:
    openshift.io/host.generated: 'true'
spec:
  host: {{ .Values.grafana.host }}
  to:
    kind: Service
    name: grafana-service
    weight: 100
  port:
    targetPort: grafana-http
  tls:
    termination: edge
  wildcardPolicy: None
