{{- if eq .Values.gateway_type "k8s_gateway"  }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana-http-route
spec:
  hostnames:
    - oh-modules.ohrancherha1-1.indra.es
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: oh-modules-gateway
      namespace: {{ .Values.namespace_oh_modules }}
      sectionName: {{ .Values.namespace_oh_modules }}
  rules:
    - backendRefs:
        - group: ''
          kind: Service
          name: grafana-service
          namespace: {{ .Release.Namespace }}
          port: 3000 
          weight: 1
      filters:
        - requestHeaderModifier:
            set:
              - name: X-Forwarded-Host
                value: {{ .Values.host_oh_modules }}
              - name: X-Forwarded-Proto
                value: {{ .Values.prot_oh_modules }}
              - name: X-Forwarded-Port
                value: '{{ if eq .Values.prot_oh_modules "http" }}80{{ else if eq .Values.prot_oh_modules "https" }}443{{ end }}'
          type: RequestHeaderModifier
      matches:
        - path:
            type: PathPrefix
            value: /grafana
{{- end }}