kind: ConfigMap
apiVersion: v1
metadata:
  name: grafana-datasources
data:
  prometheus-oh-datasource.yaml: |
    apiVersion: 1
    datasources:
    - access: proxy
      isDefault: true
      editable: true
      jsonData:
        esVersion: 0
        nodeGraph: {}
        search: {}
        serviceMap: {}
        timeInterval: 5s
        tracesToLogs: {}
      name: Prometheus OH
      secureJsonData: {}
      type: prometheus
      url: http://prometheus-server:9090
      version: 1