{{- if eq .Values.deployment_target "openshift"  }}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: oh-prometheus
  annotations:
    openshift.io/host.generated: 'true'
spec:
  host: {{ .Values.prometheus.host }}
  to:
    kind: Service
    name: prometheus-server
    weight: 100
  port:
    targetPort: {{ if .Values.ohsso.enabled }}proxy{{ else }}web{{ end }}
{{- if eq .Values.prometheus.protocol "https" }}
  tls:
    termination: edge
  wildcardPolicy: None
{{- end }}
{{- end }}