kind: Service
apiVersion: v1
metadata:
  name: prometheus-server
spec:
  ipFamilies:
    - IPv4
  ports:
    - name: web
      protocol: TCP
      port: 9090
      targetPort: web
    - name: proxy
      protocol: TCP
      port: 9091
      targetPort: proxy  
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    prometheus: oh-prometheus

