kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: oh-prometheus
  annotations:
    openshift.io/host.generated: 'true'
spec:
  host: {{ .Values.prometheus.host }}
  to:
    kind: Service
    name: prometheus-server
    weight: 100
  port:
    targetPort: proxy
  tls:
    termination: edge
  wildcardPolicy: None
