{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ohatn-back
  labels:
    app: ohatn-back
spec:
  replicas: {{ if eq .Values.global.environment.type "dev" }}1{{ else if eq .Values.global.environment.type "prod" }}2{{ end}}
  selector:
    matchLabels:
      app: ohatn-back
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ohatn-back
      annotations:
        sidecar.istio.io/inject: 'false'
    spec:
      restartPolicy: IfNotPresent
      serviceAccountName: oh-module
      imagePullSecrets:
        - name: 'oh-docker-creds'
      schedulerName: default-scheduler
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - ohatn-back
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 30
      securityContext: {}
      containers:
        - resources:
            limits:
              cpu: 300m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 750Mi
          readinessProbe:
            httpGet:
              path: /hnatna/healthcheck
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 1
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: ohatn-back
          livenessProbe:
            httpGet:
              path: /hnatna/healthcheck
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 200
            timeoutSeconds: 1
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: JVM_OPTS
              value: "-Dindrasalud.home=/hn_home -Dcom.atomikos.icatch.file=/hn_home/jta.properties -Dcom.sun.net.ssl.checkRevocation=false -Xms256m -Xmx768M"
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 2862
              protocol: TCP
            - containerPort: 2861
              protocol: UDP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: ohatn-back-jetty
              readOnly: true
              mountPath: /var/lib/jetty/webapps/ROOT/WEB-INF/jetty-env.xml
              subPath: jetty-env.xml
            - name: ohatn-back-cfg
              readOnly: true
              subPath: ArrConnections.xml
              mountPath: /hn_home/hnatna/conf/ArrConnections.xml
            - name: ohatn-back-cfg
              readOnly: true
              subPath: hnatna.properties
              mountPath: /hn_home/hnatna/conf/hnatna.properties
            - name: ohatn-back-cfg
              readOnly: true
              subPath: logback-config.xml
              mountPath: /hn_home/hnatna/conf/logback-config.xml
            - name: ohatn-back-host-props
              readOnly: true
              mountPath: /hn_home/host.properties
              subPath: host.properties
            - name: ohatn-back-integration-props
              readOnly: true
              mountPath: /hn_home/integration.properties
              subPath: integration.properties
            - name: ohatn-back-iscore-sso-props
              readOnly: true
              mountPath: /hn_home/iscore/conf
            - name: cert-domain
              mountPath: /cert/cert-domain.crt
              subPath: tls.crt
          terminationMessagePolicy: File
          image: '{{ .Values.global.docker.registry.host }}/{{ .Values.global.docker.registry.project }}/ohatn-back@{{ .Values.ohatn.sha256_back }}'
      serviceAccount: oh-module
      volumes:
        - name: ohatn-back-cfg
          configMap:
            name: ohatn-back-cfg
            defaultMode: 420
        - name: ohatn-back-jetty
          configMap:
            name: ohatn-back-jetty
            defaultMode: 420
        - name: ohatn-back-host-props
          configMap:
            name: hnhome-host-props
            defaultMode: 420
        - name: ohatn-back-integration-props
          configMap:
            name: hnhome-integration-props
            defaultMode: 420
        - name: ohatn-back-iscore-sso-props
          configMap:
            name: hnhome-iscore-sso-props
            defaultMode: 420
        - name: cert-domain
          secret:
            secretName: cert-domain
            items:
              - key: tls.crt
                path: tls.crt
            defaultMode: 420
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
{{- end }}