{{- if .Values.enabled }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: ohatn-front-cfg
data:
  env.json: |-
    {
      "services_host": "{{ .Values.global.domain.protocol }}://{{ .Values.global.domain.host }}",
      "keycloak-js-dist":"{{ .Values.global.domain.protocol }}://{{ .Values.global.domain.host }}/ARRLocalRepo/ohsso-lib.js",
      "app_theme": "./assets/css/themes/default"
    }
{{- end }}