{{- if .Values.enabled }}
{{- if eq .Values.global.domain.gateway_type "k8s_gateway"  }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ohatn-http-route
spec:
  hostnames:
    - {{ .Values.global.domain.host }}
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: oh-modules-gateway
      sectionName: oh-modules
  rules:
    - backendRefs:
        - group: ''
          kind: Service
          name: ohatn-back
          namespace: {{ .Release.Namespace }}
          port: 8080
          weight: 1
      filters:
        - requestHeaderModifier:
            set:
              - name: X-Forwarded-Host
                value: {{ .Values.global.domain.host }}
              - name: X-Forwarded-Proto
                value: {{ .Values.global.domain.protocol }}
              - name: X-Forwarded-Port
                value: '{{ if eq .Values.global.domain.protocol "http" }}80{{ else if eq .Values.global.domain.protocol "https" }}443{{ end }}'
              - name: Accept
                value: application/fhir+json;fhirVersion=3.0
              - name: Content-Type
                value: application/fhir+json;fhirVersion=3.0                
          type: RequestHeaderModifier
      matches:
        - path:
            type: PathPrefix
            value: /hnatna/
          headers:
          - type: RegularExpression
            name: Referer
            value: {{ .Values.global.domain.protocol }}://{{ .Values.global.domain.host }}/ARRLocalRepo/.*
          method: GET
    - backendRefs:
        - group: ''
          kind: Service
          name: ohatn-back
          namespace: {{ .Release.Namespace }}
          port: 8080
          weight: 1
      filters:
        - requestHeaderModifier:
            set:
              - name: X-Forwarded-Host
                value: {{ .Values.global.domain.host }}
              - name: X-Forwarded-Proto
                value: {{ .Values.global.domain.protocol }}
              - name: X-Forwarded-Port
                value: '{{ if eq .Values.global.domain.protocol "http" }}80{{ else if eq .Values.global.domain.protocol "https" }}443{{ end }}'
          type: RequestHeaderModifier
      matches:
        - path:
            type: PathPrefix
            value: /hnatna/
    - backendRefs:
        - group: ''
          kind: Service
          name: ohatn-front
          namespace: {{ .Release.Namespace }}
          port: 8080
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /ARRLocalRepo
{{- end }}
{{- end }}