{{- if .Values.enabled }}
{{- if eq .Values.global.domain.gateway-type "istio"  }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ohatn-virtual-service
spec:
  gateways:
    - oh-modules-gateway
  hosts:
    - '{{ .Values.global.domain.host }}'
  http:
    - headers:
        request:
          set:
            Accept: application/fhir+json;fhirVersion=3.0
            Content-Type: application/fhir+json;fhirVersion=3.0
            X-Forwarded-Host: {{ .Values.global.domain.host }}
            X-Forwarded-Port: '{{ if eq .Values.global.domain.protocol "http" }}80{{ else if eq .Values.global.domain.protocol "https" }}443{{ end }}'
            X-Forwarded-Proto: {{ .Values.global.domain.protocol }}
      match:
        - uri:
            prefix: /hnatna/
          method:
            exact: GET
          headers:
            Referer:
              prefix: '{{ .Values.global.domain.protocol }}://{{ .Values.global.domain.host }}/ARRLocalRepo/'
      route:
        - destination:
            host: ohatn-back
            port:
              number: 8080
    - headers:
        request:
          set:
            X-Forwarded-Host: {{ .Values.global.domain.host }}
            X-Forwarded-Port: '{{ if eq .Values.global.domain.protocol "http" }}80{{ else if eq .Values.global.domain.protocol "https" }}443{{ end }}'
            X-Forwarded-Proto: {{ .Values.global.domain.protocol }}
      match:
        - uri:
            prefix: /hnatna/
      route:
        - destination:
            host: ohatn-back
            port:
              number: 8080
    - match:
        - uri:
            prefix: /ARRLocalRepo/
      route:
        - destination:
            host: ohatn-front
            port:
              number: 8080
    - match:
        - uri:
            prefix: /ARRLocalRepo
      rewrite:
        uri: /ARRLocalRepo/
      route:
        - destination:
            host: ohatn-front
            port:
              number: 8080
{{- end }}
{{- end }}