{{- if eq .Values.global.domain.gateway_type "k8s_gateway"  }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: oh-bi-http-route
spec:
  hostnames:
    - {{ .Values.global.domain.host }}
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ .Values.global.domain.gateway }}
      sectionName: oh-modules
  rules:
    - backendRefs:
        - group: ''
          kind: Service
          name: {{ .Values.bi.module.ohbi_app_name }}
          namespace: {{ .Values.bi.module.namespace }}
          port: 8085
          weight: 1
      filters:
        - requestHeaderModifier:
            set:
              - name: X-Forwarded-Host
                value: {{ .Values.global.domain.host }}
              - name: X-Forwarded-Proto
                value: {{ .Values.global.domain.protocol }}
              - name: X-Forwarded-Port
                value: '{{ if eq .Values.global.domain.protocol "http" }}80{{ else if eq .Values.global.domain.protocol "https" }}443{{ end }}'
              - name: Accept
                value: application/fhir+json;fhirVersion=3.0
              - name: Content-Type
                value: application/fhir+json;fhirVersion=3.0
          type: RequestHeaderModifier
      matches:
        - path:
            type: PathPrefix
            value: /hi-ee/
          headers:
          - type: RegularExpression
            name: Referer
            value: {{ .Values.global.domain.protocol }}://{{ .Values.global.domain.host }}/ARRLocalRepo/.*
          method: GET
    - backendRefs:
        - group: ''
          kind: Service
          name: {{ .Values.bi.module.ohbi_app_name }}
          namespace: {{ .Values.bi.module.namespace }}
          port: 8085
          weight: 1
      filters:
        - requestHeaderModifier:
            set:
              - name: X-Forwarded-Host
                value: {{ .Values.global.domain.host }}
              - name: X-Forwarded-Proto
                value: {{ .Values.global.domain.protocol }}
              - name: X-Forwarded-Port
                value: '{{ if eq .Values.global.domain.protocol "http" }}80{{ else if eq .Values.global.domain.protocol "https" }}443{{ end }}'
          type: RequestHeaderModifier
      matches:
        - path:
            type: PathPrefix
            value: /hi-ee/
    - backendRefs:
        - group: ''
          kind: Service
          name: {{ .Values.bi.module.ohbi_app_name }}
          namespace: {{ .Values.bi.module.namespace }}
          port: 8085
          weight: 1
      filters:
        - requestHeaderModifier:
            set:
              - name: X-Forwarded-Host
                value: {{ .Values.global.domain.host }}
              - name: X-Forwarded-Proto
                value: {{ .Values.global.domain.protocol }}
              - name: X-Forwarded-Port
                value: '{{ if eq .Values.global.domain.protocol "http" }}80{{ else if eq .Values.global.domain.protocol "https" }}443{{ end }}'
              - name: Accept
                value: application/fhir+json;fhirVersion=3.0
              - name: Content-Type
                value: application/fhir+json;fhirVersion=3.0
          type: RequestHeaderModifier
      matches:
        - path:
            type: PathPrefix
            value: /oh-biservice/
          headers:
          - type: RegularExpression
            name: Referer
            value: {{ .Values.global.domain.protocol }}://{{ .Values.global.domain.host }}/ARRLocalRepo/.*
          method: GET
    - backendRefs:
        - group: ''
          kind: Service
          name: {{ .Values.bi.module.ohbi_app_name }}
          namespace: {{ .Values.bi.module.namespace }}
          port: 8085
          weight: 1
      filters:
        - requestHeaderModifier:
            set:
              - name: X-Forwarded-Host
                value: {{ .Values.global.domain.host }}
              - name: X-Forwarded-Proto
                value: {{ .Values.global.domain.protocol }}
              - name: X-Forwarded-Port
                value: '{{ if eq .Values.global.domain.protocol "http" }}80{{ else if eq .Values.global.domain.protocol "https" }}443{{ end }}'
          type: RequestHeaderModifier
      matches:
        - path:
            type: PathPrefix
            value: /oh-biservice/
{{- end }}