{{- if eq .Values.global.domain.gateway_type "istio"  }}
{{- if eq .Values.bi.database.type "Derby"  }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: oh-bi-pvc-db
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi
  storageClassName: {{ .Values.bi.module.storageclassname }}
  volumeMode: Filesystem
{{- end }}
{{- end }}