{{- if eq .Values.global.domain.gateway_type "istio"  }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
name: oh-bi-pvc-drivers
finalizers:
    - kubernetes.io/pvc-protection
spec:
accessModes:
    - ReadWriteMany
resources:
    requests:
    storage: 500Mi
storageClassName: {{ .Values.bi.module.storageclassname }}
volumeMode: Filesystem
{{- end }}