{{- if eq .Values.global.domain.gateway_type "k8s_gateway"  }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: oh-bi-back-http-route
spec:
  hostnames:
    - {{ .Values.global.domain.host }}
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ .Values.global.domain.gateway }}
      sectionName: oh-modules
  rules:
    - backendRefs:
        - group: ''
          kind: Service
          name: oh-bi-back
          namespace: {{ .Values.bi.module.namespace }}
          port: 8085
          weight: 1
      filters:
        - requestHeaderModifier:
            set:
              - name: X-Forwarded-Host
                value: {{ .Values.global.domain.host }}
              - name: X-Forwarded-Proto
                value: {{ .Values.global.domain.protocol }}
              - name: X-Forwarded-Port
                value: '{{ if eq .Values.global.domain.protocol "http" }}80{{ else if eq .Values.global.domain.protocol "https" }}443{{ end }}'
          type: RequestHeaderModifier
      matches:
        - path:
            type: PathPrefix
            value: /hi-ee/
        - path:
            type: PathPrefix
            value: /oh-biservice/
{{- end }}