kind: Deployment
apiVersion: apps/v1
metadata:
  name: oh-bi-back
spec:
  selector:
    matchLabels:
      app: oh-bi-back
  template:
    metadata:
      labels:
        app: oh-bi-back
    spec:
      imagePullSecrets:
       {{- if eq .Values.global.domain.gateway_type "istio" }}
        - name: docksdtr.indra.es
       {{- end }}
       {{- if eq .Values.global.domain.gateway_type "k8s_gateway" }}
        - name: 'oh-docker-creds'
       {{- end }}
      serviceAccountName: oh-module
      containers:
        - name: oh-bi-back
          resources:
            limits:
              cpu: 300m
              memory: 3Gi
            requests:
              cpu: 100m
              memory: 1Gi
          image: '{{ .Values.global.docker.registry.host }}/{{ .Values.global.docker.registry.project }}/oh_bi:{{ .Values.bi.tag.back }}'
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /usr/local/tomcat/webapps/oh-biservice/WEB-INF/classes/customAuthentication.properties
              subPath: customAuthentication.properties
              name: configmap
            - mountPath: /usr/local/helical-insight/conf/env.properties
              subPath: env.properties
              name: configmap
            - mountPath: /usr/local/tomcat/conf/server.xml
              subPath: server.xml
              name: configmap
            - mountPath: /usr/local/tomcat/bin/setenv.sh
              subPath: setenv.sh
              name: configmap
            - mountPath: /usr/local/helical-insight/hi-repository/System/Mail/mailConfiguration.properties
              subPath: mailConfiguration.properties
              name: configmap
            {{- if eq .Values.global.domain.gateway_type "istio" }}
            - mountPath: /usr/local/helical-insight/hi-repository/System/Drivers
              name: volume-drivers
            {{- end }}
          ports:
            - containerPort: 8443
            - containerPort: 8085
            - containerPort: 8080
            - containerPort: 25
      volumes:
        - name: configmap
          configMap:
              name: oh-bi-back-cfg
              items:
                - key: customAuthentication.properties
                  path: customAuthentication.properties
                - key: env.properties
                  path: env.properties
                - key: server.xml
                  path: server.xml
                - key: setenv.sh
                  path: setenv.sh
                - key: mailConfiguration.properties
                  path: mailConfiguration.properties
              defaultMode: 420
        {{- if eq .Values.global.domain.gateway_type "istio" }}
        - name: volume-drivers
          persistentVolumeClaim:
            claimName: oh-bi-back
        {{- end }}