{{- if eq .Values.global.domain.gateway_type "k8s_gateway"  }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ohwcviewer-http-route
spec:
  hostnames:
    - {{ .Values.global.domain.host }}
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: oh-modules-gateway
      sectionName: oh-modules
  rules:
    - backendRefs:
        - group: ''
          kind: Service
          name: webcomponent-viewer-front
          namespace: {{ .Release.Namespace }}
          port: 8080
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /webcomponent-viewer/
    - backendRefs:
        - group: ''
          kind: Service
          name: webcomponent-viewer-front
          namespace: {{ .Release.Namespace }}
          port: 8080
          weight: 1
      matches:
        - path:
            type: Exact
            value: /webcomponent-viewer
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplaceFullPath
              replaceFullPath: /webcomponent-viewer/
{{- end }}