kind: Deployment
apiVersion: apps/v1
metadata:
  name: webcomponent-viewer-front
  labels:
    app: webcomponent-viewer-front
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
  replicas: {{ if eq .Values.global.environment.type "dev" }}1{{ else if eq .Values.global.environment.type "prod" }}2{{ end}}
  selector:
    matchLabels:
      app: webcomponent-viewer-front
  template:
    metadata:
      labels:
        app: webcomponent-viewer-front
      annotations:
        sidecar.istio.io/inject: 'false'
    spec:
      imagePullSecrets:
        - name: 'oh-docker-creds'
      serviceAccountName: oh-module
      containers:
        - name: webcomponent-viewer-front
          image: {{ .Values.global.docker.registry.host }}/{{ .Values.global.docker.registry.project }}/webcomponent-viewer@{{ .Values.ohwcviewer.sha256_front }}
          ports:
            - containerPort: 8080
              protocol: TCP

          livenessProbe:
            httpGet:
              path: /webcomponent-viewer/index.html
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /webcomponent-viewer/index.html
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20

          volumeMounts:
            - name: webcomponent-viewer-front-cfg
              mountPath: /usr/share/nginx/html/webcomponent-viewer/assets/config
              readOnly: true
            - name: hnhome-ohsso-front
              readOnly: true
              mountPath: /usr/share/nginx/html/webcomponent-viewer/keycloak.json
              subPath: keycloak.json
            - name: nginx-front-cfg
              readOnly: true
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: ohsso-lib
              readOnly: true
              mountPath: /usr/share/nginx/html/webcomponent-viewer/ohsso-lib.js
              subPath: ohsso-lib.js
          resources:
            limits:
              cpu: 50m
              memory: 48Mi
            requests:
              cpu: 25m
              memory: 16Mi
          imagePullPolicy: Always

      volumes:
        - name: webcomponent-viewer-front-cfg
          configMap:
            name: webcomponent-viewer-front-cfg
        - name: hnhome-ohsso-front
          configMap:
            name: hnhome-ohsso-front
            defaultMode: 420
        - name: nginx-front-cfg
          configMap:
            name: nginx-front-cfg
            defaultMode: 420
        - name: ohsso-lib
          configMap:
            name: ohsso-lib
            defaultMode: 420
