name: Update Index

on:
  push:
    branches: [ main ]
    paths:
      - '**.tgz'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
      - name: Helm Installation
        uses: azure/setup-helm@v1.1
        with:
          version: v3.7.0
      - name: Update Index
        env:
          GITHUB_TOKEN: ${{ secrets.SGV_TOKEN }}          
        run: |
          helm repo index .
          git config --global user.name 'salvadorgilv'
          git config --global user.email 'salvadorgilv@gmail.com'
          git add index.yaml
          git commit  -m "Update chart index"
          git push https://"${{ secrets.SGV_TOKEN }}"@github.com/onesaithealthcare/onesaithealthcare-charts.git
